### PR TITLE
fix(schema): reject duplicate field IDs at schema construction

### LINKED ISSUE #593: bug: schema does not reject multiple field ids
### Bug

We allow this:

```golang
sc := iceberg.NewSchema(0,
	        ...
		iceberg.NestedField{
			Type: &iceberg.StructType{
				FieldList: []iceberg.NestedField{
					{
						Type: typ,
						ID:   6,
						Name: "inner_op",
					},
					{
						Type:     typ,
						ID:       6,
						Name:     "inner_req",
						Required: true,
					},
					...
				},
			},
			ID:       5,
			Name:     "struct",
			Required: true,
		},
                ...
	)
```

while java rejects this:

```java
new Schema(
        Types.NestedField.required(1, "id", Types.LongType.get()),
        Types.NestedField.optional(2, "top", type),
        Types.NestedField.optional(3, "arr", Types.ListType.ofRequired(4, type)),
        Types.NestedField.required(
            5,
            "struct",
            Types.StructType.of(
                Types.NestedField.optional(6, "inner_op", type),
                Types.NestedField.required(6, "inner_req", type),
                Types.NestedField.optional(
                    8,
                    "struct_arr",
                    Types.StructType.of(Types.NestedField.optional(9, "deep", type))))));
```

```
  java.lang.IllegalArgumentException: Multiple entries with same key: 6=struct.inner_req and 6=struct.inner_op
...
	at org.apache.iceberg.types.IndexByName.byId(IndexByName.java:81)
	at org.apache.iceberg.types.TypeUtil.indexNameById(TypeUtil.java:174)
	at org.apache.iceberg.Schema.lazyIdToName(Schema.java:225)
	at org.apache.iceberg.Schema.<init>(Schema.java:154)
```

We could probably verify this in the same place as java, in schema.init()

### PR DESCRIPTION
**Pull request by alliasgher**
## Summary

`NewSchema` silently accepted multiple fields sharing the same positive integer ID. The Java implementation throws `IllegalArgumentException` at construction time with _"Multiple entries with same key: 6=struct.inner_req and 6=struct.inner_op"_.

Adds `checkDuplicateFieldIDs` — a lightweight recursive walk over `NestedField`, `*StructType`, `*ListType`, and `*MapType` that only reads field IDs without dereferencing type pointers. It is called from `NewSchemaWithIdentifiers` before returning the schema. A duplicate positive ID panics with `ErrInvalidSchema`, consistent with the `indexByName` panic for duplicate field names (schema.go line 851).

Non-positive IDs (`-1` etc. used as "unassigned" placeholders in schema builders) are skipped so existing internal usage is unaffected.

Fixes #593

## Test plan

- [x] `go test ./...`
- [x] `gofmt` clean
- [x] `TestNewSchemaPanicsOnDuplicateFieldIDs`: top-level duplicate + the exact nested-struct case from the bug report.

Signed-off-by: Ali <alliasgher123@gmail.com>

### CODE REVIEW

File: schema_test.go [hunk 1]
```diff
@@ -934,6 +934,42 @@ func TestIndexByNameDuplicateFieldNames(t *testing.T) {
 	assert.ErrorContains(t, err, "multiple fields for name col")
 }
 
+func TestNewSchemaPanicsOnDuplicateFieldIDs(t *testing.T) {
```
Comment (laskoviymishka) [inline schema_test.go:937]: The two test cases cover top-level and struct-nested duplicates. 

Missing:
- List element ID colliding with another field — e.g., ListType{ElementID: 2} when field ID 2 already exists
- Map key/value ID colliding — e.g., MapType{KeyID: 3} when field ID 3 already exists
- Deeply nested duplicate — struct inside a list inside a map

These are the cases where the recursive walker earns its keep, without them, you're only testing flat/one-level-deep traversal.

File: schema.go [hunk 2]
```diff
@@ -76,9 +76,60 @@ func NewSchemaWithIdentifiers(id int, identifierIDs []int, fields ...NestedField
...
+					ErrInvalidSchema, f.ID, prev, f.Name)
+			}
+			seen[f.ID] = f.Name
+		}
+
+		// Recurse into nested types without touching the type pointer for
+		// primitives — only StructType, ListType, and MapType carry child fields.
+		switch t := f.Type.(type) {
+		case *StructType:
+			if t != nil {
```
Comment (laskoviymishka) [inline schema.go:113]: The nil check is defensive — f.Type.(*StructType) matching in the switch already means f.Type is a non-nil interface holding a *StructType. The only way t is nil is if the interface holds a typed nil ((*StructType)(nil)), which would be a bug elsewhere. 

Fine to keep for safety, just noting it's belt-and-suspenders.

**Review by laskoviymishka — CHANGES_REQUESTED** [review]
Main ask: add list/map test coverage, aside that - LGTM

File: schema_test.go (hunk 1 above)
Comment (alliasgher) [reply schema_test.go:937]: Added in 73952c3 — list element ID collision, map key ID collision, and a deeply nested case (struct inside a list inside a map value).

File: schema.go (hunk 2 above)
Comment (alliasgher) [reply schema.go:113]: Agreed, left it in for the typed-nil case.

**Review by laskoviymishka — APPROVED** [review]

File: schema.go [hunk 3]
```diff
@@ -76,9 +76,60 @@ func NewSchemaWithIdentifiers(id int, identifierIDs []int, fields ...NestedField
...
+		panic(err)
+	}
+
 	return s
 }
 
+// checkDuplicateFieldIDs recursively walks a list of fields and returns an
+// error if any field ID appears more than once anywhere in the tree.
+func checkDuplicateFieldIDs(seen map[int]string, fields []NestedField) error {
+	for _, f := range fields {
```
Comment (zeroshade) [inline schema.go:98]: could probably simplify this by having 

```go
if seen == nil {
    seen = make(map[int]string)
}
```

That way you can just use `checkDuplicateFieldIDs(nil, fields)` for the top level call of the recursion instead of needing to explicitly create the map externally.

**Review by zeroshade — CHANGES_REQUESTED** [review]
Looks good, just one nitpick!

File: schema.go (hunk 3 above)
Comment (alliasgher) [reply schema.go:98]: Applied in 21445bd.

**Review by zeroshade — APPROVED** [review]
