### PR TITLE
fix(catalog/glue): case insensitive type match

### LINKED ISSUE #479: "table X.Y is not an iceberg table" on a valid iceberg table
### Apache Iceberg version

None

### Please describe the bug 🐞

We are appending data to a table in AWS Glue Catalog using PyIceberg & PyArrow
then try to load the table from `iceberg-go` but `LoadTable` fails
with "table X.Y is not an iceberg table". The table parameters map
contains key "table_type" as required by [Glue catalog implementation](https://github.com/apache/iceberg-go/blob/237da8fd2034d772cd5969a372d2e411e3dfc66d/catalog/glue/glue.go#L697-L699)
but its value is not all-upper "ICEBERG", rather it's lower case.

On the writer side (PyIceberg/PyArrow) we use the [AWS Glue Iceberg REST endpoint](https://docs.aws.amazon.com/glue/latest/dg/connect-glu-iceberg-rest.html).

Both [PyIceberg](https://github.com/apache/iceberg-python/blob/main/pyiceberg/catalog/glue.py#L376) and [java](https://github.com/apache/iceberg/blob/061ae58986db3495ff3af6f1932a96dd086e5fbd/aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java#L329) implementations
perform the same check ignoring the case of the value.
It seems that the condition check should be implemented in case-insensitive
way for `iceberg-go` too, wdyt?

### PR DESCRIPTION
**Pull request by vbekiaris**
table_type and database_type key values are now
compared against "ICEBERG" string in case-insensitive way
(similar to how PyIceberg and Java implementations work).

Fixes #479

### CODE REVIEW

File: catalog/glue/glue.go [hunk 1]
```diff
@@ -694,7 +695,7 @@ func (c *Catalog) getTable(ctx context.Context, database, tableName string) (*ty
 		return nil, fmt.Errorf("failed to get table %s.%s: %w", database, tableName, err)
 	}
 
-	if tblRes.Table.Parameters[tableTypePropsKey] != glueTypeIceberg {
+	if strings.ToUpper(tblRes.Table.Parameters[tableTypePropsKey]) != glueTypeIceberg {
```
Comment (zeroshade) [inline catalog/glue/glue.go]: any particular reason to use `ToUpper` here and `EqualFold` below instead of just using `EqualFold` in both cases?

Comment (vbekiaris) [reply catalog/glue/glue.go]: no particular reason - changed in 9b918b62288b2b2bd9af3b34b1312d40d152065f

**Comment by vbekiaris** [comment]
thanks @zeroshade for the quick review!
