### PR TITLE
fix(catalog): ensure we close metadata writers

### LINKED ISSUE #644: A blob.Writer was never closed (table corrupted)
### Apache Iceberg version

v0.4.0

### Please describe the bug 🐞

I am running a Go container on AWS Fargate that receives messages from SQS and executes a ReplaceDataFiles transaction on a REST catalog. My REST catalog is Polaris (hosted by Snowflake on Open Catalog).

I have been testing this container for about 2 days. Early this morning, I got the following warning in the logs:

2025/12/06 11:25:05 A blob.Writer writing to "grib2_dev/mrms/metadata/6a1ad4c5-32dc-4ebe-ab06-eaf9db430800-m3.avro" was never closed (/go/pkg/mod/github.com/apache/iceberg-go@v0.4.0/io/blob.go:178)

After this warning occurred, all further transactions errored out with the following message:

error processing messages: error merging: error replacing: error creating transaction: blob (key "grib2_dev/mrms/metadata/6a1ad4c5-32dc-4ebe-ab06-eaf9db430800-m3.avro") (code=NotFound): operation error S3: GetObject, https response error StatusCode: 404, RequestID: EX6437WV478680PJ, HostID: 4S2e8WzoIqHpjbG6ob+rrWfplLNsKjVm02+QDyWPjDsNfICdEsH1hNv9hVN6jZ57dBFjh1H+tW4=, NoSuchKey: The specified key does not exist.

I am somewhat confident the error is not in my code as the initial warning was not emitted by any of my error handlers (I don't know where it originated). It seems like some transitory error prevented a manifest writer from closing without being caught.

### PR DESCRIPTION
**Pull request by zeroshade**
While looking into #644 I found exactly one location which seems that we could end up failing to close a writer. So this fixes that spot and properly uses our `CheckedClose` utility to ensure we close the file writer.

In theory this should fix #644 but I haven't yet been able to write a good test for this.

### CODE REVIEW

**Comment by zeroshade** [comment]
@tlarsendataguy could you take a look and see if you can confirm this fixes the issue you saw?

File: catalog/internal/utils.go [hunk 1]
```diff
@@ -52,18 +54,14 @@ func WriteTableMetadata(metadata table.Metadata, fs icebergio.WriteFileIO, loc s
 	case table.MetadataCompressionCodecGzip:
 		compressWriter = gzip.NewWriter(out)
 		writer = compressWriter
+		defer internal.CheckedClose(compressWriter, &err)
 	default:
 		return fmt.Errorf("unsupported write metadata compression codec: %s", compression)
```
Comment (ferhatelmas) [inline catalog/internal/utils.go]: Change seems correct functionally. 

If it's fine to refactor a bit, I would move validation to the top so that if wrong input codec is given, it can skip creating a writer and closing it completely, instead return early

Comment (zeroshade) [reply catalog/internal/utils.go]: is the new version pretty much what you were thinking?

Comment (ferhatelmas) [reply catalog/internal/utils.go]: yes, looks good to me

**Review by kevinjqliu — APPROVED** [review]
LGTM! Thanks
