### PR TITLE
fix(table): close underlying counter in manifest creation

### LINKED ISSUE #681: Warning "blob.Writer ... .avro was never closed"   followed by error  "(code=NotFound)...StatusCode: 404...HostID: , NoSuchKey: "
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

I believe this is related to a previously reported bug: #644 

It looks like there were some fixes (#666 and #667 ) made for this issue 

However, I am still seeing this issue 

Below is my simplified transaction function. I have a single pod writing to an Iceberg table using Nessie as a REST catalog.

And I am getting the following warning:

> 2026/01/18 19:42:13 A blob.Writer writing to "u011720265/numberdpattrs_f030e24e-3c91-4a94-a323-35b3e176eac9/metadata/3ce12426-33ad-4b1f-ba33-5785663bd484-m2.avro" was never closed (github.com/apache/iceberg-go@v0.4.0/io/blob.go:178)

it is followed by error:

> time="2026-01-18T19:42:12Z" level=error msg="Error in appending recordReader to transaction (transaction) - blob (key "u011720265/numberdpattrs_f030e24e-3c91-4a94-a323-35b3e176eac9/metadata/b1f32157-1731-420b-90c9-7a206b029370-m2.avro") (code=NotFound): operation error S3: GetObject, https response error StatusCode: 404, RequestID: phx-1:ge7kLmOBIvlIQQCiYKKkzHJiQMQlc9QFybP4Tpzt9ug9K2zEMqSBANXyoPwBIxiG, HostID: , NoSuchKey: "

I am using following function to make transaction.

```
func transaction(ctx context.Context, dataTable *icebergtbl.Table, arrowSchema *arrow.Schema, arrowRecords []arrow.RecordBatch, icebergProperties iceberg.Properties) (*icebergtbl.Table, error) {

	txn := dataTable.NewTransaction()

	recordReader, err := array.NewRecordReader(arrowSchema, arrowRecords)
	if err != nil {
		log.Errorf("Error in creating new record reader (transaction) - %s", err)
		return nil, err
	}
	defer recordReader.Release()

	err = txn.Append(ctx, recordReader, icebergProperties)
	if err != nil {
		log.Errorf("Error in appending recordReader to transaction (transaction) - %s", err)
		return nil, err
	}

	dataTable, err = txn.Commit(ctx)
	if err != nil {
		log.Errorf("Error in committing to table (transaction)- %s", err)
		return nil, err
	}
	
	return dataTable, nil
}
```

Any suggestions ?

### PR DESCRIPTION
**Pull request by ferhatelmas**
related to #644, fixes #681

### CODE REVIEW

**Comment by ferhatelmas** [comment]
Yes, by reverting source changes:

```
go test ./table/...
--- FAIL: TestCreateManifestClosesUnderlyingFile (0.00s)
    snapshot_producers_test.go:404:
                Error Trace:    /Users/ferhat/Dev/apache/iceberg-go/table/snapshot_producers_test.go:404
                Error:          Should be empty, but was [table-location/metadata/9aa08f09-4164-4a58-a6fa-82b5d7983517-m1.avro]
                Test:           TestCreateManifestClosesUnderlyingFile
                Messages:       all file writers should be closed after createManifest, but these are still open: [table-location/metadata/9aa08f09-4164-4a58-a6fa-82b5d7983517-m1.avro]
--- FAIL: TestOverwriteExistingManifestsClosesUnderlyingFile (0.00s)
    snapshot_producers_test.go:456:
                Error Trace:    /Users/ferhat/Dev/apache/iceberg-go/table/snapshot_producers_test.go:456
                Error:          Should be empty, but was [table-location/metadata/9ce8a0cd-26dd-462e-8998-34679265a621-m1.avro]
                Test:           TestOverwriteExistingManifestsClosesUnderlyingFile
                Messages:       all file writers should be closed after existingManifests, but these are still open: [table-location/metadata/9ce8a0cd-26dd-462e-8998-34679265a621-m1.avro]
FAIL
FAIL    github.com/apache/iceberg-go/table      0.287s
ok      github.com/apache/iceberg-go/table/internal     (cached)
ok      github.com/apache/iceberg-go/table/substrait    (cached)
```

File: table/snapshot_producers.go [hunk 1]
```diff
@@ -482,20 +491,20 @@ func (sp *snapshotProducer) deleteDataFile(df iceberg.DataFile) *snapshotProduce
...
+func (sp *snapshotProducer) newManifestWriter(spec iceberg.PartitionSpec) (_ *iceberg.ManifestWriter, _ string, _ *internal.CountingWriter, _ io.Closer, err error) {
 	out, path, err := sp.newManifestOutput()
 	if err != nil {
-		return nil, "", nil, err
+		return nil, "", nil, nil, err
 	}
 
 	counter := &internal.CountingWriter{W: out}
 	wr, err := iceberg.NewManifestWriter(sp.txn.meta.formatVersion, counter, spec,
 		sp.txn.meta.CurrentSchema(), sp.snapshotID)
```
Comment (zeroshade) [inline table/snapshot_producers.go:502]: Hmm, so the issue is that closing the manifest writer isn't sufficient to close the underlying output writer. Could modify the CountingWriter so that it is an `io.WriteCloser` and propagates a call to `Close` to the underlying writer, and then update the `ManifestWriter` to properly call close on the underlying writer when Close is called? That way we don't need to return the separate closer?

Is that worthwhile over this current solution?

Comment (ferhatelmas) [reply table/snapshot_producers.go:502]: I looked into that option, because it seems better at first but the way of `CountingWriter` usage in certain cases would require bigger refactoring. Since this approach was already used by `manifests` method, sticked to this.

Comment (zeroshade) [reply table/snapshot_producers.go:502]: Makes sense. sounds good. Thanks!
