### PR TITLE
fix(table): populate WriteTask.SortOrderID in data file writers

### LINKED ISSUE #842: fix: populate WriteTask.SortOrderID from table metadata
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

Parent: #829

`WriteTask.SortOrderID` at `writer.go:41` is declared but never populated — it defaults to 0 at every construction site. 

The Iceberg spec requires each data file's manifest entry to record which sort order was used (`sort-order-id`). `DataFileBuilder.SortOrderID()` already exists at `manifest.go:2244`.

### PR DESCRIPTION
**Pull request by alliasgher**
## Summary

The `SortOrderID` field on `WriteTask` was declared but never set by any producer, so every data file written via the standard/partitioned/rolling/equality-delete paths ended up with a nil `sort_order_id` in the manifest entry. This leaves readers with no way to know which sort order the file was written against.

This PR threads `SortOrderID` end-to-end:

* `WriteFileInfo` gains a `SortOrderID` field and `DataFileStatistics.ToDataFile` now calls `DataFileBuilder.SortOrderID` so the value lands on the final `DataFile`.
* `arrow_utils.filesToDataFiles`, `writer.writeFile`, and `writerFactory` all pass the table's default sort order id down to `WriteFileInfo`, and the equality-delete / position-delete / rolling data writer paths populate the `WriteTask.SortOrderID` accordingly.

Fixes #842

## Test plan

- [x] `go test ./table/...`
- [x] `go vet ./...`
- [x] New assertion: `withSortOrderIDMatching` added to `defaultPositionDeleteMatching` in `TestPositionDeletePartitionedFanoutWriterProcessBatch`; `mockDataFile` gains an overridable sort order id so this path is covered end-to-end.

Signed-off-by: Ali <ali@kscope.ai>

### CODE REVIEW

File: table/equality_delete_writer.go
Comment (laskoviymishka) [inline table/equality_delete_writer.go:201]: unpartitioned write task missing sort-order definition.

File: table/arrow_utils.go [hunk 1]
```diff
@@ -1617,6 +1617,7 @@ func positionDeleteRecordsToDataFiles(ctx context.Context, rootLocation string,
 					FileCount:   fileCount,
 					Schema:      iceberg.PositionalDeleteSchema,
 					Batches:     batch,
+					SortOrderID: meta.defaultSortOrderID,
```
Comment (laskoviymishka) [inline table/arrow_utils.go:1620]: same issue in the unpartitioned position-delete path. Missing SortOrderID: meta.defaultSortOrderID.

File: table/internal/utils.go [hunk 2]
```diff
@@ -236,7 +236,7 @@ func (d *DataFileStatistics) PartitionValue(field iceberg.PartitionField, sc *ic
 	return lowerT.Val.Any()
 }
 
-func (d *DataFileStatistics) ToDataFile(schema *iceberg.Schema, spec iceberg.PartitionSpec, path string, format iceberg.FileFormat, content iceberg.ManifestEntryContent, filesize int64, partitionValues map[int]any) iceberg.DataFile {
+func (d *DataFileStatistics) ToDataFile(schema *iceberg.Schema, spec iceberg.PartitionSpec, path string, format iceberg.FileFormat, content iceberg.ManifestEntryContent, filesize int64, partitionValues map[int]any, sortOrderID int) iceberg.DataFile {
```
Comment (laskoviymishka) [inline table/internal/utils.go:239]: nit: this signature became very heavy, worth to refactor, can be follow up.

File: table/internal/interfaces.go [hunk 3]
```diff
@@ -117,6 +117,10 @@ type WriteFileInfo struct {
 	WriteProps       any
 	Content          iceberg.ManifestEntryContent
 	EqualityFieldIDs []int
+	// SortOrderID is the sort order id used when writing the data file.
+	// Used to populate the manifest entry's sort_order_id. Defaults to
+	// table.UnsortedSortOrderID (0) for unsorted writes.
```
Comment (laskoviymishka) [inline table/internal/interfaces.go]: this comment smell fishy to me, why only this field must have such descriptive comment?

**Review by laskoviymishka — CHANGES_REQUESTED** [review]
Thanks for tackling this — the core approach is correct and the partitioned paths are threaded properly. However, I think this needs another pass before merging:

Both equalityDeleteRecordsToDataFiles (equality_delete_writer.go:201) and positionDeleteRecordsToDataFiles (arrow_utils.go:1613) construct WriteTask{} without SortOrderID in their unpartitioned branches. The zero-value means these files always get sort_order_id = 0 regardless of the table's actual default sort order.

The partitioned branches of the same functions set it correctly — this looks like an oversight.

Also needs more tests:

- No test for the standard data write path (writerFactory / rolling data writer) with a non-zero sort order
- No test for unpartitioned position-delete or equality-delete writes, which is exactly where the bug above lives
- A round-trip test (write manifest, read it back, verify sort_order_id)

The unpartitioned path bug needs a fix with corresponding test coverage.

File: table/internal/utils.go (hunk 2 above)
Comment (alliasgher) [reply table/internal/utils.go:239]: Agreed — will clean this up in a follow-up PR rather than widen the scope of this one.

**Comment by alliasgher** [comment]
Thanks for the review — pushed the extra tests:

- `TestRollingDataWriter/TestWriterFactoryPropagatesSortOrderID` covers the standard data write path (writerFactory + rolling data writer) with a non-zero default sort order.
- `TestPositionDeleteUnpartitionedSortOrderID` and `TestEqualityDeleteUnpartitionedSortOrderID` cover the unpartitioned branches of `positionDeleteRecordsToDataFiles` and `equalityDeleteRecordsToDataFiles`.
- `TestManifests/TestManifestRoundTripSortOrderID` writes a data file with a sort_order_id through `WriteManifest`, reads it back via `ReadManifest`, and verifies the value round-trips.

One clarification question on the first point — could you take another look at [`equality_delete_writer.go` line 208](https://github.com/apache/iceberg-go/pull/875/files#diff-a041da9e1b29acca53a8b8d8b5fca7be8b16c3bce3f3bb8fcfd7c2c90b063a72) and [`arrow_utils.go` line 1620](https://github.com/apache/iceberg-go/pull/875/files#diff-38f706ad9be1ff50afebbbfe2050ed3be8090a9bdc3ae08b74a08b4769e9fdfc)? I believe both unpartitioned `WriteTask{}` constructions already set `SortOrderID: meta.defaultSortOrderID` in the diff, but let me know if I'm missing something or if you were pointing at a different site.

File: table/internal/interfaces.go (hunk 3 above)
Comment (alliasgher) [reply table/internal/interfaces.go]: Good point — removed in c6c8e83 to match the style of the rest of the struct.

**Comment by laskoviymishka** [comment]
Thx! With new test it's clear now!

**Review by laskoviymishka — APPROVED** [review]

**Comment by laskoviymishka** [comment]
@tanmayrauth can you also review this one, i suggest to close #885, as dupe.

File: table/internal/parquet_files_test.go [hunk 4]
```diff
@@ -261,7 +261,7 @@ func TestMetricsPrimitiveTypes(t *testing.T) {
 
 	stats := format.DataFileStatsFromMeta(internal.Metadata(meta), getCollector(), mapping)
 	df := stats.ToDataFile(tblMeta.CurrentSchema(), tblMeta.PartitionSpec(), "fake-path.parquet",
-		iceberg.ParquetFile, iceberg.EntryContentData, meta.GetSourceFileSize(), nil)
+		iceberg.ParquetFile, iceberg.EntryContentData, meta.GetSourceFileSize(), nil, 0)
```
Comment (zeroshade) [inline table/internal/parquet_files_test.go]: Do we have any tests with a non-zero sort order id?

File: table/pos_delete_partitioned_fanout_writer_test.go [hunk 5]
```diff
@@ -503,7 +503,125 @@ func (m *dataFileMatcher) Format(val iceberg.DataFile) string {
 }
 
 // defaultPositionDeleteMatching is a convenience preset for the options we want to match for position delete matching
-var defaultPositionDeleteMatching = []dataFileMatcherOption{withContentTypeMatching(), withColumnSizesMatching(), withCountMatching(), withFileFormatMatching(), withSpecIDMatching(), withPartitionMatching(), withCountMatching()}
+var defaultPositionDeleteMatching = []dataFileMatcherOption{withContentTypeMatching(), withColumnSizesMatching(), withCountMatching(), withFileFormatMatching(), withSpecIDMatching(), withPartitionMatching(), withCountMatching(), withSortOrderIDMatching()}
+
+func intPtr(i int) *int { return &i }
```
Comment (zeroshade) [inline table/pos_delete_partitioned_fanout_writer_test.go]: Don't we have a generic helper function for this somewhere? If not, can you convert this to be a generic one?

```go
func ptrOf[T any](i T) *T { return &i }
```

**Review by zeroshade — APPROVED** [review]
Looks good, just a couple nit pick comments

File: table/internal/utils.go (hunk 2 above)
Comment (alliasgher) [reply table/internal/utils.go:239]: Follow-up PR opened: #888.

File: table/internal/parquet_files_test.go (hunk 4 above)
Comment (alliasgher) [reply table/internal/parquet_files_test.go]: Added in 0015b1f — `TestMetricsPrimitiveTypes` now uses a non-zero sort order id (7) and asserts the resulting DataFile carries it.

File: table/pos_delete_partitioned_fanout_writer_test.go (hunk 5 above)
Comment (alliasgher) [reply table/pos_delete_partitioned_fanout_writer_test.go]: Replaced with a generic `ptr[T any]` in 0015b1f. There's one in `snapshots_test.go` but it's scoped to `package table_test` (external) whereas this file is in `package table` (internal), so I added a local generic helper. Happy to consolidate further if you'd prefer moving the helper elsewhere.

Comment (zeroshade) [reply table/pos_delete_partitioned_fanout_writer_test.go]: It's fine for now. We can probably clean this up with a follow-up but not necessary for this PR. Thanks!
