### PR TITLE
fix(table): include expected vs found snapshot id in AssertRefSnapshotID errors (#940)

### LINKED ISSUE #940: feat(table): include expected vs found snapshot id in AssertRefSnapshotID errors
Parent: #829

`AssertRefSnapshotID.Validate` (`table/requirements.go`) returns errors of the form `requirement failed: assert ref snapshot id` without including the actual versus expected snapshot ids. Java's equivalent `AssertRefSnapshotID` formats the mismatch into the message so the operator can see what changed — iceberg-go does not, which makes commit-conflict triage harder than it should be.

The struct already carries the expected `ref` name and snapshot id, and `Validate` receives the current `Metadata` from which the actual head can be read. Format both into the error: `"requirement failed: ref %q expected snapshot %d, found %d"`. Update the corresponding test in `table/requirements_test.go`. Mechanical wrap; matches the pattern used by other typed errors in the file.

### PR DESCRIPTION
**Pull request by tanmayrauth**
Format ref name, expected snapshot id, and found snapshot id into all three error paths so operators can see what changed during commit conflicts. Also fixes incorrect pointer formatting with %d.

Fixes #940

### CODE REVIEW

**Comment by tanmayrauth** [comment]
@laskoviymishka  @zeroshade  will you be able to review this PR?

File: table/requirements.go [hunk 1]
```diff
@@ -180,14 +180,14 @@ func (a *assertRefSnapshotID) Validate(meta Metadata) error {
 
 	if r != nil {
 		if a.SnapshotID == nil {
-			return fmt.Errorf("requirement failed: %s %s was created concurrently", r.SnapshotRefType, a.Ref)
+			return fmt.Errorf("requirement failed: ref %q was created concurrently, found %d", a.Ref, r.SnapshotID)
```
Comment (zeroshade) [inline table/requirements.go]: Why use `%q` here instead of `"%s"` ?

**Review by zeroshade — COMMENTED** [review]
just one nitpick

File: table/requirements.go (hunk 1 above)
Comment (tanmayrauth) [reply table/requirements.go]: Yeah, ref name might not have special char. Will update revert it to %s.

**Review by laskoviymishka — CHANGES_REQUESTED** [review]
Nice small fix, and the `%d`-on-pointer bug is definitely worth fixing — printing pointer addresses as snapshot IDs is very misleading.

Before merge, I’d only ask for one small change: please keep the ref name formatting as `%q` instead of manual `\"%s\". %q` is the idiomatic Go version and handles names with quotes/newlines correctly.

Optional but worth considering: the new wording drifts a bit from Java/PyIceberg, especially around branch/tag and expected id <e> != <f>. If we care about cross-client log parity, this PR is a good place to align it.

**Comment by zeroshade** [comment]
Where possible we definitely want to try to keep cross-client log parity so that's definitely a good idea

**Review by zeroshade — APPROVED** [review]
