### PR TITLE
fix(table): logging error when deleting old metadata

### LINKED ISSUE #411: table.doCommit call fails when metadata file is already removed
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

When `write.metadata.delete-after-commit.enabled` is set to true, the [deleteOldMetadata](https://github.com/apache/iceberg-go/blob/5cf1bdba4ee442bd61f2a8d9e5c64d3f42a75763/table/table.go#L222) function will delete the old metadata files from the underlying fs. If this deletion fails, then the `doCommit` call will fail, even though the commit itself actually succeeded. This will happen fx. if a metadata file to be deleted has already been deleted by an external entity.

This problem occurs when using the [Lakekeeper rest catalog implementation](https://github.com/lakekeeper/lakekeeper). Lakekeeper will also delete old metadata files when committing if `write.metadata.delete-after-commit.enabled` is set to true.

For reference, pyIceberg will simply log any failed delete. Should the goIceberg client maybe use the same approach?

I am happy to submit a PR to change this behaviour.

### PR DESCRIPTION
**Pull request by Shreyas220**
Fixes #411

### CODE REVIEW

File: table/table.go [hunk 1]
```diff
@@ -230,12 +228,12 @@ func deleteOldMetadata(fs io.IO, baseMeta, newMeta Metadata) error {
 
 		for _, file := range toRemove {
 			if err := fs.Remove(file); err != nil {
-				return fmt.Errorf("failed to delete old metadata file %s: %w", file, err)
+				//Log the error instead of raising it when deleting old metadata files, as an external entity like a compactor may have already deleted them
+				fmt.Printf("Warning: Failed to delete old metadata file %s: %v", file, err)
```
Comment (zeroshade) [inline table/table.go]: use `log.Printf` so that we can easily update and manipulate this in the future.

**Review by zeroshade — COMMENTED** [review]
Can we get a test for this so that we don't end up with an issue in the future?

**Comment by zeroshade** [comment]
Just needs to fix the linting issue first
