### PR TITLE
fix(table): prevent index out of range error in buildManifestEvaluator

### LINKED ISSUE #691: bug: index out of range in buildManifestEvaluator
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

Hi all,

I've encountered an index out of range error in [table/scanner.go](https://github.com/apache/iceberg-go/blob/c082326e5d23ff0b2e10ec09847e6e943f0d1860/table/scanner.go#L246).
The current implementation tries to get the relevant partition spec by index instead of looping over the slice and filtering by specID:
```
spec := scan.metadata.PartitionSpecs()[specID]
```

We had implemented some table maintenance tasks and we think one of them removed old metadata files. I think this lead to one of the partition specs getting removed. Therefore the partition spec with specID 1 was at slice index 0. I'm not sure if this is allowed and the spec with specID 0 should have never been removed (related [question](https://github.com/apache/iceberg/issues/15108)), or if scanner.go should have just got the partition spec by specID instead of index. If the latter, I can contribute a fix.

### PR DESCRIPTION
**Pull request by ErenDursun**
fixes #691

Previously, the buildManifestEvaluator method directly accessed the PartitionSpecs array by index without validating that the requested specID actually exists in the partition specs. This could cause an index out of bounds error.

This change adds a proper lookup using slices.IndexFunc to find the partition spec by its ID and returns an error if the spec is not found, improving error handling and robustness.

### CODE REVIEW

File: table/utils.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+	"github.com/apache/iceberg-go"
+)
+
+func getPartitionSpecByID(specs []iceberg.PartitionSpec, specID int) (*iceberg.PartitionSpec, error) {
+	i := slices.IndexFunc(specs, func(spec iceberg.PartitionSpec) bool {
+		return spec.ID() == specID
+	})
+	if i < 0 {
+		return nil, fmt.Errorf("partition spec with id %d not found", specID)
```
Comment (zeroshade) [inline table/utils.go]: should we use a specific `ErrNotFound` that we wrap and embed?

Comment (ErenDursun) [reply table/utils.go]: thanks for the feedback, done 👍

File: table/metadata.go [hunk 2]
```diff
@@ -1155,6 +1155,7 @@ func maxBy[S ~[]E, E any](elems S, extract func(e E) int) int {
 var (
 	ErrInvalidMetadataFormatVersion = errors.New("invalid or missing format-version in table metadata")
 	ErrInvalidMetadata              = errors.New("invalid metadata")
+	ErrPartitionSpecNotFound        = errors.New("partition spec not found")
```
Comment (ferhatelmas) [inline table/metadata.go:1161]: Since we add a new sentinel error, IMO we also need to wrap this for metadata builder `GetSpecByID` line https://github.com/apache/iceberg-go/pull/692/changes#diff-57293572e24e73b264cc6bd07f43c295ce7c89f2c238453b8729db574e2bcaf2R921?

File: table/utils.go [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+package table
+
+import (
+	"fmt"
+	"slices"
+
+	"github.com/apache/iceberg-go"
+)
+
+func getPartitionSpecByID(specs []iceberg.PartitionSpec, specID int) (*iceberg.PartitionSpec, error) {
```
Comment (ferhatelmas) [inline table/utils.go]: Does it make sense to add it to interface `PartitionSpecByID` via `commonMetadata` instead of duplication?

File: table/scanner.go
Comment (ferhatelmas) [inline table/scanner.go]: nit: not related to this PR but evaluator could be outside as well and could be reused instead of creating for each call

File: table/utils.go [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+	i := slices.IndexFunc(specs, func(spec iceberg.PartitionSpec) bool {
+		return spec.ID() == specID
+	})
+	if i < 0 {
+		return nil, fmt.Errorf("%w: id %d", ErrPartitionSpecNotFound, specID)
+	}
+
+	return &specs[i], nil
```
Comment (ferhatelmas) [inline table/utils.go]: There is a logical difference between here and [above](https://github.com/apache/iceberg-go/pull/692/changes#diff-57293572e24e73b264cc6bd07f43c295ce7c89f2c238453b8729db574e2bcaf2R924): a pointer to actual spec vs a pointer to its copy.

File: table/metadata.go (hunk 2 above)
Comment (ErenDursun) [reply table/metadata.go:1161]: good catch 👍 done

File: table/utils.go (hunk 3 above)
Comment (ErenDursun) [reply table/utils.go]: I think it does. Did you mean something like [this](https://github.com/apache/iceberg-go/pull/692/changes/25e664b01e4cdb8b94fa73530494cebc1d6e70ca)?
I also removed the error return value, because it's an interface method now and whether it is an error or not might depend on the context from where it's called (e.g. [here](https://github.com/apache/iceberg-go/pull/692/changes#diff-eb806166d1b9d570a36b8506d2b9ada56126a32ca94b1eb12d6de03973e292c2R407-R411) it's not).

File: table/utils.go (hunk 4 above)
Comment (ErenDursun) [reply table/utils.go]: Should be fixed. Can you please double-check this? We want to return a (ref to a) copy, right?

File: table/utils.go (hunk 3 above)
Comment (ferhatelmas) [reply table/utils.go]: yes, thanks, it looks good

File: table/utils.go (hunk 4 above)
Comment (ferhatelmas) [reply table/utils.go]: It has reference type fields (slice) so copy isn't deep. I don't see any updates but only reads which might not make a difference either way in the existing code. However, pointer signals to me that I am getting the actual reference. It's not the case here, it could be misleading. 

That being said, similar pattern exists  for `Snapshot`, `SortOrder` and `Schema`. Only schema is clear because it is a list of pointers. Others are doing copy (value -> pointer -> value). We might want to address all of them at once for consistency. For now, ref to copy is fine I believe to align with existing code. 

cc @zeroshade

Comment (zeroshade) [reply table/utils.go]: Yea, we can address this but let's address it all at once in a future PR
