### PR TITLE
fix(table): use proper data file names

### LINKED ISSUE #697: Data file names always use hardcoded "00000" partition ID instead of tracking actual sequence
### Apache Iceberg version

v0.4.0

## Description
Go implementation is missing the fileCount field entirely. The Java version has an AtomicInteger fileCount that increments with each file generated.

### Current Behavior

The `GenerateDataFileName` function in `table/writer.go` hardcodes the partition ID to `00000`:

```go
func (w WriteTask) GenerateDataFileName(extension string) string {
    // Mimics the behavior in the Java API:
    // https://github.com/apache/iceberg/blob/a582968975dd30ff4917fbbe999f1be903efac02/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java#L92-L101
    return fmt.Sprintf("00000-%d-%s.%s", w.ID, w.Uuid, extension)
}
```

This results in all data files having the same `00000` prefix regardless of when they were written:

```
00000-0-7cebe869-463c-47d6-8fd6-64f4cb58f49e.parquet
00000-0-34a719df-d820-493e-871b-83ad8c2144d4.parquet
00000-0-d3036e2e-3980-4271-877b-33c7a32ea43e.parquet
```

### Expected Behavior

According to the [Iceberg Java implementation](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java), the file naming format is:

```
{partitionId}-{taskId}-{operationId}-{fileCount}.{extension}
```

Where:
- `partitionId` - identifies the partition (should increment or be unique per partition)
- `taskId` - identifies the task/writer
- `operationId` - UUID for the operation
- `fileCount` - file counter within the task

Files written in different commits should have incrementing identifiers.

### Impact

| Aspect | Affected? |
|--------|-----------|
| Data integrity | No - UUIDs ensure uniqueness |
| Query correctness | No - Iceberg metadata tracks files properly |
| Iceberg spec compliance | Partial deviation from Java naming convention |
| Operational visibility | Yes - cannot determine write order from filenames |
| Debugging | Yes - harder to trace which commit created which file |

### Environment

- **iceberg-go version**: v0.4.0
- **Go version**: 1.23.x

### Reproduction Steps

1. Create an Iceberg table
2. Append data multiple times using `table.Append()`
3. List the data files in S3/storage
4. Observe all files have `00000` prefix

### Suggested Fix

The `OutputFileFactory` equivalent in iceberg-go should track:
1. A counter that persists across commits (or derives from table metadata)
2. Proper partition ID based on the partition being written to

This would bring the Go implementation in line with the Java reference implementation.

---

**Labels:** `enhancement`, `writer`, `spec-compliance`

### PR DESCRIPTION
**Pull request by zeroshade**
fixes #697

Follows the same standard as the java implementation to generate data file names appropriately.

Adds a test to confirm the name generation.

### CODE REVIEW

File: table/rolling_data_writer.go [hunk 1]
```diff
@@ -157,12 +162,15 @@ func (r *RollingDataWriter) flushToDataFile(batch []arrow.RecordBatch, outputDat
...
 		cnt := int(r.factory.counter.Add(1) - 1)
+		fileCount := int(r.fileCount.Add(1))
 
 		yield(WriteTask{
-			Uuid:    *r.factory.args.writeUUID,
-			ID:      cnt,
-			Schema:  r.factory.taskSchema,
-			Batches: batch,
+			Uuid:        *r.factory.args.writeUUID,
+			ID:          cnt,
```
Comment (ferhatelmas) [inline table/rolling_data_writer.go:174]: nit: not exactly related to this PR but isn't `cnt` supposed to initialize by the given `args.counter` as in unpartitioned case?

File: table/writer.go [hunk 2]
```diff
@@ -33,15 +33,18 @@ import (
...
 	Schema      *iceberg.Schema
 	Batches     []arrow.RecordBatch
 	SortOrderID int
 }
 
 func (w WriteTask) GenerateDataFileName(extension string) string {
 	// Mimics the behavior in the Java API:
-	// https://github.com/apache/iceberg/blob/a582968975dd30ff4917fbbe999f1be903efac02/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java#L92-L101
-	return fmt.Sprintf("00000-%d-%s.%s", w.ID, w.Uuid, extension)
+	// https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java
```
Comment (ferhatelmas) [inline table/writer.go]: IMO [permalink](https://github.com/apache/iceberg/blob/03ed4ba9af4e47d32bdb22b7e3d033eb2a4b2c83/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java#L93-L103) was better if file or line changes

File: table/arrow_utils.go [hunk 3]
```diff
@@ -1338,13 +1338,17 @@ func recordsToDataFiles(ctx context.Context, rootLocation string, meta *Metadata
...
 				cnt, _ := nextCount()
+				fileCount++
 				t := WriteTask{
-					Uuid:    *args.writeUUID,
-					ID:      cnt,
-					Schema:  taskSchema,
-					Batches: batch,
+					Uuid:        *args.writeUUID,
+					ID:          cnt,
+					PartitionID: 0, // unpartitioned tables use 0
```
Comment (ferhatelmas) [inline table/arrow_utils.go]: does it make sense to use unpartitioned spec id directly?

File: table/arrow_utils.go [hunk 4]
```diff
@@ -1338,13 +1338,17 @@ func recordsToDataFiles(ctx context.Context, rootLocation string, meta *Metadata
 		tasks := func(yield func(WriteTask) bool) {
 			defer stopCount()
 
+			fileCount := 0
 			for batch := range binPackRecords(args.itr, 20, targetFileSize) {
```
Comment (ferhatelmas) [inline table/arrow_utils.go]: aside, 20 seems like the default used in multiple locations, might benefit from putting it into a constant

File: table/writer_test.go [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func TestGenerateDataFileName(t *testing.T) {
+	tests := []struct {
+		name        string
+		task        WriteTask
+		extension   string
+		wantPattern string // regex pattern to match
```
Comment (ferhatelmas) [inline table/writer_test.go]: this doesn't seem to be a regex, maybe just rename to `want` and drop the comment

File: table/writer_test.go [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+import (
+	"testing"
+
+	"github.com/google/uuid"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func TestGenerateDataFileName(t *testing.T) {
+	tests := []struct {
```
Comment (ferhatelmas) [inline table/writer_test.go:29]: worth of adding a test with partition id and file count more than 5 digits?

File: table/rolling_data_writer.go (hunk 1 above)
Comment (zeroshade) [reply table/rolling_data_writer.go:174]: that's a good point and worthwhile to fix in here.

File: table/writer.go (hunk 2 above)
Comment (zeroshade) [reply table/writer.go]: that's a good point, i'll put it back

File: table/writer_test.go (hunk 5 above)
Comment (zeroshade) [reply table/writer_test.go]: yea, that comment is from a previous version of this

File: table/writer_test.go (hunk 6 above)
Comment (zeroshade) [reply table/writer_test.go:29]: I don't think there's necessarily much worth to it, but it's also a pretty low cost addition so I'll add it

File: internal/utils.go [hunk 7]
```diff
@@ -164,12 +165,15 @@ func RecoverError(err *error) {
...
+	current.Store(int64(start))
+
 	return func(yield func(int) bool) {
 		for {
-			if !yield(start) {
+			if !yield(int(current.Load())) {
 				return
 			}
-			start++
+			current.Add(1)
```
[the remark this answers is not in the document]
Comment (kevinjqliu) [reply internal/utils.go]: this seems valid, @zeroshade wdyt?

File: table/rolling_data_writer.go [hunk 8]
```diff
@@ -156,13 +166,16 @@ func (r *RollingDataWriter) flushToDataFile(batch []arrow.RecordBatch, outputDat
 	}
 
 	task := iter.Seq[WriteTask](func(yield func(WriteTask) bool) {
-		cnt := int(r.factory.counter.Add(1) - 1)
+		cnt, _ := r.factory.nextCount()
```
[the remark this answers is not in the document]
Comment (zeroshade) [reply table/rolling_data_writer.go:169]: we made sure the base counter is safe for concurrent use, so I think this should be fine as long as we make sure that `args.counter` is defined as having to be safe for concurrent use.
