### PR TITLE
fix: Clickhouse does not support "null" as partition spec metadata

### LINKED ISSUE #344: `partition-spec` is invalid while producing V1 metadata
### Apache Iceberg version

None

### Please describe the bug 🐞

The `partition-spec` is null, and should be equal to the spec in `partition-specs` that is being pointed at by `current-partition-spec`.

For V1, it should be:

```
{
    "partition-spec": [],
...
}
```

Because it is required.

Instead of:

```
{
    "partition-spec": null,
...
}
...
```

```json
{
    "schema": {
        "type": "struct",
        "fields": [
            {
                "type": "int",
                "id": 1,
                "name": "id",
                "required": true
            }
        ],
        "schema-id": 0,
        "identifier-field-ids": []
    },
    "partition-spec": null,
    "format-version": 1,
    "table-uuid": "dd93fa46-a1a7-43bb-8748-6cc7eff107a3",
    "location": "s3a://warehouse/iceberg/iceberg-test-2.db/test-table-2",
    "last-updated-ms": 1742412491193,
    "last-column-id": 1,
    "schemas": [
        {
            "type": "struct",
            "fields": [
                {
                    "type": "int",
                    "id": 1,
                    "name": "id",
                    "required": true
                }
            ],
            "schema-id": 0,
            "identifier-field-ids": []
        }
    ],
    "current-schema-id": 0,
    "partition-specs": [
        {
            "spec-id": 0,
            "fields": []
        }
    ],
    "default-spec-id": 0,
    "last-partition-id": 999,
    "properties": {},
    "snapshot-log": null,
    "metadata-log": null,
    "sort-orders": [
        {
            "order-id": 0,
            "fields": []
        }
    ],
    "default-sort-order-id": 0,
    "refs": null
}
```

### PR DESCRIPTION
**Pull request by arnaudbriche**
Hi,

I'm working on [a tool that leverage this package](https://github.com/agnosticeng/icepq) to support adding / removing / merging Parquet files from ClickHouse with an UDF.  

After upgrading this package (and removing a lot of code thx to your last commits) I got errors from ClickHouse (again) at query time.

I nailed the issue down to the "partition-spec" metadata of the manifest file.
When there is no field in the partition spec, the current code write a "null" JSON document that cause errors with ClickHouse.
I just replaced "null" with "[]" in this case and things are working ok again.

Fixes #344

### CODE REVIEW

**Comment by Fokko** [comment]
I noticed this yesterday while checking the code for the release: https://github.com/apache/iceberg-go/issues/344

So thank you @arnaudbriche for fixing this right away, much appreciated!

**Comment by Fokko** [comment]
@arnaudbriche It looks like the linter is sad. It would also be nice if we could test this in some way so we don't break this in the future.

File: manifest_test.go [hunk 1]
```diff
@@ -867,6 +868,16 @@ func (m *ManifestTestSuite) TestManifestEntryBuilder() {
 	m.Assert().Equal(0, *data.SortOrderID())
 }
 
+func (m *ManifestTestSuite) TestManifestWriterMeta() {
+	sch := NewSchema(0, NestedField{ID: 0, Name: "test01", Type: StringType{}})
+	w, err := NewManifestWriter(2, io.Discard, *UnpartitionedSpec, sch, 1)
+	m.Require().NoError(err)
+	md, err := w.meta()
+	m.Require().NoError(err)
+	m.Assert().NotEqual("null", string(md["partition-spec"]))
```
Comment (zeroshade) [inline manifest_test.go]: you don't need the `Assert()` portion, you can just do `m.NotEqual` and `m.Equal`, the `m.Assert()` part is a convenience for passing it around

**Review by zeroshade — APPROVED** [review]
Thanks for the quick fix!
