### PR TITLE
fix(table): read retention table properties as defaults in ExpireSnapshots

### LINKED ISSUE #839: fix: read snapshot retention properties as defaults in ExpireSnapshots
Parent: #831

`ExpireSnapshots()` at `transaction.go:210` requires explicit `WithRetainLast(n)` / `WithOlderThan(d)` options. It never reads `min-snapshots-to-keep`, `max-snapshot-age-ms`, or `max-ref-age-ms` from table properties, even though the keys and defaults are defined in `properties.go:90-97`. Java reads these automatically so that tables with retention properties expire correctly with no caller configuration.

### PR DESCRIPTION
**Pull request by alliasgher**
## Summary

`ExpireSnapshots` required callers to always pass `WithRetainLast` and `WithOlderThan`; it never consulted the table-level retention properties (`min-snapshots-to-keep`, `max-snapshot-age-ms`, `max-ref-age-ms`), even though their keys and defaults are defined in `properties.go`. Tables that set these properties via a catalog would not honor them during snapshot expiry, diverging from the Java implementation.

**Fix:** read the three retention properties from table metadata and use them as the last-resort fallback in the `cmp.Or` chains for `maxRefAgeMs`, `minSnapshotsToKeep`, and `maxSnapshotAgeMs`. When a property is absent the `math.MaxInt` constants apply, preserving current behaviour for callers that pass explicit options.

Fixes #839

## Test plan

- [x] `go test ./...`
- [x] `gofmt -l` clean
- [x] New test `TestExpireSnapshotsUsesTableProperties`: creates a table with `min-snapshots-to-keep=2` and `max-snapshot-age-ms=0` set as properties, calls `ExpireSnapshots()` with no options, and asserts exactly 2 snapshots survive.

Signed-off-by: Ali <alliasgher123@gmail.com>

### CODE REVIEW

File: table/transaction.go [hunk 1]
```diff
@@ -220,6 +220,15 @@ func (t *Transaction) ExpireSnapshots(opts ...ExpireSnapshotsOpt) error {
 		opt(&cfg)
 	}
 
+	// Read table-level retention properties as the last-resort defaults,
+	// mirroring the Java implementation. When neither the ref nor the
+	// caller provides a value, fall back to the table property; when the
+	// table property is also absent use the constant default (math.MaxInt,
+	// meaning "keep everything").
```
Comment (laskoviymishka) [inline table/transaction.go:227]: The defaults here are math.MaxInt — meaning "keep everything" when no property is set. That's correct and matches Java.

One thing: GetInt parses via strconv.ParseInt(..., 10, 64) and returns int. Then you cast to int64. On 64-bit systems int == int64 so this is fine, but on 32-bit (if that's ever a target) math.MaxInt as int would be math.MaxInt32, then cast to int64 would be 2147483647 — not math.MaxInt64. Probably doesn't matter, but worth a note.

File: table/table_test.go [hunk 2]
```diff
@@ -1705,6 +1705,62 @@ func (t *TableWritingTestSuite) TestExpireSnapshotsNoOpWhenNothingToExpire() {
...
+
+	ident := table.Identifier{"default", "expire_props_v" + strconv.Itoa(t.formatVersion)}
+	// Set table-level retention properties — no caller options will be passed to
+	// ExpireSnapshots, so these must be picked up automatically.
+	meta, err := table.NewMetadata(t.tableSchemaPromotedTypes, iceberg.UnpartitionedSpec,
+		table.UnsortedSortOrder, t.location, iceberg.Properties{
+			table.PropertyFormatVersion: strconv.Itoa(t.formatVersion),
+			table.MinSnapshotsToKeepKey: "2",
+			table.MaxSnapshotAgeMsKey:   "0", // expire everything older than "now"
+			table.MaxRefAgeMsKey:        strconv.FormatInt(int64(table.MaxRefAgeMsDefault), 10),
```
Comment (laskoviymishka) [inline table/table_test.go]: This sets max-ref-age-ms to math.MaxInt, which is exactly what GetInt returns when the property is absent. 

This line has no effect and is test noise. 

Remove it, the test should prove that missing properties fall back to defaults correctly, not that explicitly-set-to-default properties work.

**Review by laskoviymishka — APPROVED** [review]
Thanks for contribution! Good fix: ExpireSnapshots should read table-level retention properties as defaults, matching Java. 

Two nits: removing the error returns is a silent behavioral change, and the test has a couple of rough edges.

File: table/table_test.go (hunk 2 above)
Comment (alliasgher) [reply table/table_test.go]: Removed in d1bd3cd and replaced with a comment explaining the intent — the absent property is now the thing being tested, not an explicitly-set default.

File: table/transaction.go (hunk 1 above)
Comment (alliasgher) [reply table/transaction.go:227]: Noted, happy to add a `GetInt64` helper and use it here as a follow-up if you'd like.

**Comment by laskoviymishka** [comment]
@tanmayrauth can you review this one, and close #883 as dupe?

**Review by zeroshade — APPROVED** [review]
