### PR TITLE
fix(catalog/glue): create table with required fields

### LINKED ISSUE #407: Glue catalog create table doesn't work with schema with required columns
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

Current Glue catalog [create table implementation](https://github.com/apache/iceberg-go/blob/main/catalog/glue/glue.go#L231-L233) simply use Glue Create Table API to create the table in Glue data catalog and use the metadata file created by Glue. 

However, Glue Create Table API doesn't have a way to check or specify if a column is required in a schema, hence, all columns in the table metadata file created by Glue is an optional column.

Checking iceberg-python and iceberg-rust, both clients have implementations that creates the metadata file using FileIO and then creates the table using that metadata file created.
* https://github.com/apache/iceberg-rust/blob/main/crates/catalog/glue/src/catalog.rs#L396-L399
* https://github.com/apache/iceberg-python/blob/main/pyiceberg/catalog/glue.py#L451

### PR DESCRIPTION
**Pull request by zeroshade**
fixes #407

Update and improve the Glue catalog CreateTable to properly set the parameters on the table itself and the columns (such as iceberg.field.id and iceberg.field.optional).

Also, write out the metadata first and then pass the location to Glue as part of creating the table.

### CODE REVIEW

**Review by zeroshade — COMMENTED** [review]
@lliangyu-lin can you take a look and confirm if this fixes the issue you filed?

**Comment by lliangyu-lin** [comment]
@zeroshade Thank you for working on this! The implementation looks good to me. 

But somehow when I test locally with actual AWS Credentials, I'm getting 400 from Glue `InvalidInputException: Cannot use reserved parameters table_type or metadata_location while creating an iceberg table`. I checked other iceberg client implementations and they did use table_type and metadata_location as well. So let me do some check and get back to you on this.

File: catalog/glue/glue.go [hunk 1]
```diff
@@ -231,29 +238,42 @@ func (c *Catalog) CatalogType() catalog.Type {
...
+		TableType: aws.String("EXTERNAL_TABLE"),
 		StorageDescriptor: &types.StorageDescriptor{
-			Location: aws.String(cfg.Location),
-			Columns:  schemaToGlueColumns(schema),
+			Location: aws.String(staged.Metadata().Location()),
+			Columns:  schemaToGlueColumns(schema, true),
 		},
+		Description: tableDescription,
 	}
 	_, err = c.glueSvc.CreateTable(ctx, &glue.CreateTableInput{
```
Comment (lliangyu-lin) [inline catalog/glue/glue.go:281]: Found the issue why glue is complaining about table type and metadata location.
The block below is not needed for create table and needs to be removed. It should only be used when asking Glue to create the metadata file.
```
OpenTableFormatInput: &types.OpenTableFormatInput{
			IcebergInput: &types.IcebergInput{
				MetadataOperation: types.MetadataOperationCreate,
			},
		},
```
Tested locally that once this is removed, create table is working correctly.

File: catalog/glue/glue.go [hunk 2]
```diff
@@ -231,29 +238,42 @@ func (c *Catalog) CatalogType() catalog.Type {
 // CreateTable creates a new Iceberg table in the Glue catalog.
 // AWS Glue will create a new table and a new metadata file in S3 with the format: metadataLocation/metadata/00000-00000-00000-00000-00000.metadata.json.
```
Comment (lliangyu-lin) [inline catalog/glue/glue.go]: nit: Should we update the comment here?

Comment (zeroshade) [reply catalog/glue/glue.go]: yup!

**Review by lliangyu-lin — APPROVED** [review]
LGTM! Thanks @zeroshade

File: catalog/glue/glue.go [hunk 3]
```diff
@@ -65,6 +65,10 @@ const (
 	Endpoint        = "glue.endpoint"
 	MaxRetries      = "glue.max-retries"
 	RetryMode       = "glue.retry-mode"
+
+	icebergFieldIDKey       = "iceberg.field.id"
+	icebergFieldOptionalKey = "iceberg.field.optional"
+	icebergFieldCurrentKey  = "iceberg.field.current"
```
Comment (Fokko) [inline catalog/glue/glue.go:71]: I forgot about this one. Will it ever be `false`? 🤔 The current schema should be stored in Glue.

Comment (Fokko) [reply catalog/glue/glue.go:71]: Interesting: https://github.com/apache/iceberg/pull/3888/

**Review by Fokko — APPROVED** [review]
This looks great @zeroshade Thanks!

**Comment by Fokko** [comment]
Thanks for working on this @zeroshade and thanks for the review @lliangyu-lin 🙌
