### PR TITLE
fix(manifest): ManifestEntry partition field schema should be dynamically generated

### LINKED ISSUE #305: Wrong Avro schema for ManifestEntry
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

I'm trying to use the package to create and maintain Iceberg tables from independently generated Parquet files on S3.
I'm using the various builders to create and persist Avro and JSON metadata files to S3.

I'm hitting an issue with ManifestV2, more specifically the DatFile structure.

It looks like this package uses static Avro schema definitions in JSON format; here the schema for ManifestEntryV2:

```json
{
    "type": "record",
    "name": "manifest_entry",
    "fields": [
        {"name": "status", "type": "int", "field-id": 0},
        {"name": "snapshot_id", "type": ["null", "long"], "field-id": 1},
        {"name": "sequence_number", "type": ["null", "long"], "field-id": 3},
        {"name": "file_sequence_number", "type": ["null", "long"], "field-id": 4},
        {
            "name": "data_file",
            "type": {
                "type": "record",
                "name": "r2",
                "fields": [
                    {"name": "content", "type": "int", "doc": "Type of content stored by the data file", "field-id": 134},
                    {"name": "file_path", "type": "string", "doc": "Location URI with FS scheme", "field-id": 100},
                    {
                        "name": "file_format",
                        "type": "string",
                        "doc": "File format name: avro, orc, or parquet",
                        "field-id": 101
                    },
                    {
                        "name": "partition",
                        "type": {
                            "type": "record",
                            "name": "r102",
                            "fields": [
                                {"field-id": 1000, "name": "VendorID", "type": ["null", "int"]},
                                {
                                    "field-id": 1001,                                        
                                    "name": "tpep_pickup_datetime",
                                    "type": ["null", {"type": "int", "logicalType": "date"}]
                                }
                            ]
                        },
                        "field-id": 102
                    },
                    {"name": "record_count", "type": "long", "doc": "Number of records in the file", "field-id": 103},
                    {"name": "file_size_in_bytes", "type": "long", "doc": "Total file size in bytes", "field-id": 104},                        
                    {
                        "name": "column_sizes",
                        "type": [
                            "null",
                            {
                                "type": "array",
                                "items": {
                                    "type": "record",
                                    "name": "k117_v118",
                                    "fields": [
                                        {"name": "key", "type": "int", "field-id": 117},
                                        {"name": "value", "type": "long", "field-id": 118}
                                    ]
                                },
                                "logicalType": "map"
                            }
                        ],
                        "doc": "Map of column id to total size on disk",                            
                        "field-id": 108
                    },
                    {
                        "name": "value_counts",
                        "type": [
                            "null",
                            {
                                "type": "array",
                                "items": {
                                    "type": "record",
                                    "name": "k119_v120",
                                    "fields": [
                                        {"name": "key", "type": "int", "field-id": 119},
                                        {"name": "value", "type": "long", "field-id": 120}
                                    ]
                                },
                                "logicalType": "map"
                            }
                        ],
                        "doc": "Map of column id to total count, including null and NaN",                            
                        "field-id": 109
                    },
                    {
                        "name": "null_value_counts",
                        "type": [
                            "null",
                            {
                                "type": "array",
                                "items": {
                                    "type": "record",
                                    "name": "k121_v122",
                                    "fields": [
                                        {"name": "key", "type": "int", "field-id": 121},
                                        {"name": "value", "type": "long", "field-id": 122}
                                    ]
                                },
                                "logicalType": "map"
                            }
                        ],
                        "doc": "Map of column id to null value count",                            
                        "field-id": 110
                    },
                    {
                        "name": "nan_value_counts",
                        "type": [
                            "null",
                            {
                                "type": "array",
                                "items": {
                                    "type": "record",
                                    "name": "k138_v139",
                                    "fields": [
                                        {"name": "key", "type": "int", "field-id": 138},
                                        {"name": "value", "type": "long", "field-id": 139}
                                    ]
                                },
                                "logicalType": "map"
                            }
                        ],
                        "doc": "Map of column id to number of NaN values in the column",                            
                        "field-id": 137
                    },
                    {
                        "name": "lower_bounds",
                        "type": [
                            "null",
                            {
                                "type": "array",
                                "items": {
                                    "type": "record",
                                    "name": "k126_v127",
                                    "fields": [
                                        {"name": "key", "type": "int", "field-id": 126},
                                        {"name": "value", "type": "bytes", "field-id": 127}
                                    ]
                                },
                                "logicalType": "map"
                            }
                        ],
                        "doc": "Map of column id to lower bound",                            
                        "field-id": 125
                    },
                    {
                        "name": "upper_bounds",
                        "type": [
                            "null",
                            {
                                "type": "array",
                                "items": {
                                    "type": "record",
                                    "name": "k129_v130",
                                    "fields": [
                                        {"name": "key", "type": "int", "field-id": 129},
                                        {"name": "value", "type": "bytes", "field-id": 130}
                                    ]
                                },
                                "logicalType": "map"
                            }
                        ],
                        "doc": "Map of column id to upper bound",                            
                        "field-id": 128
                    },
                    {
                        "name": "key_metadata",
                        "type": ["null", "bytes"],
                        "doc": "Encryption key metadata blob",                            
                        "field-id": 131
                    },
                    {
                        "name": "split_offsets",
                        "type": ["null", {"type": "array", "items": "long", "element-id": 133}],
                        "doc": "Splittable offsets",                            
                        "field-id": 132
                    },
                    {
                        "name": "equality_ids",
                        "type": ["null", {"type": "array", "items": "int", "element-id": 136}],
                        "doc": "Field ids used to determine row equality for delete files",
                        "field-id": 135
                    },
                    {
                        "name": "sort_order_id",
                        "type": ["null", "int"],
                        "doc": "Sort order ID",                            
                        "field-id": 140
                    }
                ]
            },
            "field-id": 2
        }
    ]
}
```

The part that is causing issue is this:

```json
{
    "name": "partition",
    "type": {
        "type": "record",
        "name": "r102",
        "fields": [
            {"field-id": 1000, "name": "VendorID", "type": ["null", "int"]},
            {
                "field-id": 1001,                                        
                "name": "tpep_pickup_datetime",
                "type": ["null", {"type": "int", "logicalType": "date"}]
            }
        ]
    },
    "field-id": 102
}
```

This is not the right schema type for partition as of the spec. It looks more like an example from the doc or something.

Here's what the spec says about the partition field:

required | required | required | 102 partition | struct<...> | Partition data tuple, schema based on the partition spec output using partition field ids for the struct field ids
-- | -- | -- | -- | -- | --

This is not very clear to me, but it sounds like the type is a dynamically generated Avro record type. Not sure how it can be implemented with the current static Avro schema approach.

Logically,  my experiment fails with the following error message: `"Data: PartitionData: avro: missing required field VendorID"`.

### PR DESCRIPTION
**Pull request by arnaudbriche**
Avro schemas for Iceberg metadata files are now built dynamically with code.
I know this changes a lot of code, but I did not find other less intrusive ways to fix the issue.

### CODE REVIEW

File: utils.go [hunk 1]
```diff
@@ -238,3 +239,68 @@ func avroEncode[T any](key string, version int, vals []T, out io.Writer) error {
...
+		sch = avro.NewPrimitiveSchema(avro.Bytes, nil)
+	case *BooleanType:
+		sch = avro.NewPrimitiveSchema(avro.Boolean, nil)
+	case *Float32Type:
+		sch = avro.NewPrimitiveSchema(avro.Float, nil)
+	case *Float64Type:
+		sch = avro.NewPrimitiveSchema(avro.Double, nil)
+	case *DateType:
+		sch = avro.NewPrimitiveSchema(avro.Int, avro.NewPrimitiveLogicalSchema(avro.Date))
+	default:
```
Comment (zeroshade) [inline utils.go]: missing some types here

File: utils.go [hunk 2]
```diff
@@ -238,3 +239,68 @@ func avroEncode[T any](key string, version int, vals []T, out io.Writer) error {
...
+		aField, err := nestedFieldToAvroField(field)
+
+		if err != nil {
+			return nil, err
+		}
+
+		aFields = append(aFields, aField)
+	}
+
+	return avro.NewRecordSchema("r102", "", aFields)
```
Comment (zeroshade) [inline utils.go]: should this be "r102"? Or should this be more dynamic?

File: manifest.go [hunk 3]
```diff
@@ -613,31 +633,37 @@ func WriteManifestList(out io.Writer, files []ManifestFile) error {
...
 	switch version {
 	case 1:
-		key = internal.ManifestListV1Key
+		sch = internal.MustNewManifestListV1Schema()
 	case 2:
-		key = internal.ManifestListV2Key
+		sch = internal.MustNewManifestListV2Schema()
 	default:
 		return fmt.Errorf("%w: non-recognized version %d", ErrInvalidArgument, version)
 	}
```
Comment (zeroshade) [inline manifest.go]: for the ManifestList schema and others that don't need the dynamic part, it's better to have a cache of the schemas than to build it from scratch each time.

File: manifest.go [hunk 4]
```diff
@@ -292,10 +307,15 @@ func (b *ManifestV2Builder) KeyMetadata(km []byte) *ManifestV2Builder {
...
 func (b *ManifestV2Builder) Build() ManifestFile {
+	if b.m.partitionType == nil {
+		b.m.partitionType = UnpartitionedSpec.PartitionType(nil)
+	}
+
 	return b.m
 }
 
 type manifestFileV2 struct {
+	partitionType      *StructType
```
Comment (zeroshade) [inline manifest.go:336]: Could this be integrated with the `FieldSummary` instead of being at the top level here?

Comment (zeroshade) [reply manifest.go:336]: In either case, we should probably be populating this after reading in a manifest file too, right?

File: internal/utils.go [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+
+func MustNewUnionSchema(types []avro.Schema, opts ...avro.SchemaOption) *avro.UnionSchema {
+	s, err := avro.NewUnionSchema(types, opts...)
+
+	if err != nil {
+		panic(err)
+	}
+
+	return s
+}
```
Comment (zeroshade) [inline internal/utils.go]: these can all be simplified with a simple

```go
func Must[T any](v T, err error) T {
    if err != nil {
        panic(err)
    }
    return v
}
```

and then just using that generic method around the rest of the calls instead. Honestly, we probably can just have that utility function and not bother having these at all, just calling `Must(avro.NewUnionSchema(.....))` etc.

File: internal/manifest_list_v2.go [hunk 6]
```diff
@@ -0,0 +1,100 @@
+package internal
+
+import (
+	"github.com/hamba/avro/v2"
+)
+
+func MustNewManifestListV2Schema() avro.Schema {
```
Comment (zeroshade) [inline internal/manifest_list_v2.go]: since this is a static schema, can we cache it rather than building it on demand?

File: internal/manifest_list_v1.go [hunk 7]
```diff
@@ -0,0 +1,142 @@
...
+				avro.NewNullSchema(),
+				avro.NewPrimitiveSchema(avro.Long, nil),
+			}),
+			avro.WithDoc("Deleted rows count"),
+			avro.WithProps(map[string]any{"field-id": 514}),
+		),
+	})
+}
+
+func MustNewPartitionSchema() avro.Schema {
```
Comment (zeroshade) [inline internal/manifest_list_v1.go]: again, can this static schema be cached rather than built on demand

File: internal/manifest_list_v1.go [hunk 8]
```diff
@@ -0,0 +1,142 @@
+package internal
+
+import (
+	"github.com/hamba/avro/v2"
+)
+
+func MustNewManifestListV1Schema() avro.Schema {
```
Comment (zeroshade) [inline internal/manifest_list_v1.go]: same as other comments

File: internal/manifest-entry-v1.json [hunk 9]
```diff
@@ -0,0 +1,182 @@
+{
```
Comment (zeroshade) [inline internal/manifest-entry-v1.json]: where does this json file get used?

**Review by zeroshade — CHANGES_REQUESTED** [review]
A bunch of comments plus you need to add the Apache license blurb at the top of the new files.

File: utils.go (hunk 1 above)
Comment (arnaudbriche) [reply utils.go]: Sure. Do we agree that we only need to handle primitive/scalar types here ?

File: utils.go (hunk 2 above)
Comment (arnaudbriche) [reply utils.go]: Not sure. The spec seems not to enforce any specific name here.

File: internal/manifest-entry-v1.json (hunk 9 above)
Comment (arnaudbriche) [reply internal/manifest-entry-v1.json]: I just used them as an example to build the dynamic schema building code. I removed them now that they are no longer useful.

File: manifest.go (hunk 4 above)
Comment (arnaudbriche) [reply manifest.go:336]: Not sure if it belongs to `FieldSummary`. 
We also need to be able to do `Avro` -> `Iceberg` schema conversion to populate the field on read.

File: utils.go (hunk 1 above)
Comment (zeroshade) [reply utils.go]: As far as I'm aware, yes. You can't partition on a struct/list/map type to my knowledge.

File: utils.go (hunk 2 above)
Comment (zeroshade) [reply utils.go]: @kevinjqliu @Fokko @nastra any of you happen to know there answer on this one?

Comment (arnaudbriche) [reply utils.go]: Here is how Pyiceberg derives the record name: https://github.com/apache/iceberg-python/blob/efc8b5ac0f16717f776e034ecf9a9e9bdabd8424/pyiceberg/utils/schema_conversion.py#L543

Comment (zeroshade) [reply utils.go]: seems reasonable we should do the same then :)

File: utils.go (hunk 1 above)
Comment (arnaudbriche) [reply utils.go]: Done.

Comment (arnaudbriche) [reply utils.go]: Let me know if you see missing ones.

File: manifest.go (hunk 4 above)
Comment (arnaudbriche) [reply manifest.go:336]: I have done `Avro` <--> `Iceberg` schema conversions.
Can you please help me with the populate part ? Maybe point me to the right part of the code ?

**Comment by arnaudbriche** [comment]
I'm trying to create and maintain Iceberg tables from externally generated Parquet files with this lib.
The goal is for Clickhouse to be able to query the table.

While writing the various Avro metadata files with the lib, I encountered many errors from ClickHouse, which complained about missing metadata on the Avro manifest files.

As of the spec, Manifest files must have specific metadata to be valid: https://iceberg.apache.org/spec/#manifests

I thus created the `WriteManifestEntries` that writes the Avro Manifest files with proper metadata.
Not sure how to make the `WriteEntries` method of `manifestFileV1` and `manifestFileV2` write compliant Avro Manifest files.

**Comment by zeroshade** [comment]
@arnaudbriche i'll take a look and see if I can condense and simplify this a bit for you, probably quicker than going back and forth like this

**Comment by zeroshade** [comment]
@arnaudbriche would it be easier for you to enable maintainers to push to this branch and update or should I just open a new PR with the changes?

**Comment by arnaudbriche** [comment]
@zeroshade 

I cannot find the "Allow edits from maintainers" button. Can you point-out where it is supposed to be ?

**Comment by arnaudbriche** [comment]
Seems like the feature does not exists when the fork repository is owner by an Organization.
I just gave you write access to the fork repository. 
Is that ok ?

**Comment by zeroshade** [comment]
Looks like i have read access but not write access currently :frowning:

**Comment by zeroshade** [comment]
Ah i had to accept the invite

**Comment by zeroshade** [comment]
@arnaudbriche can you take a look at my updated version here and make sure that it works with what you were trying for clickhouse? Feel free to comment on the actual API also if you like

@Fokko @kevinjqliu I'd also love any feedback you two might have as far as the manifest writing APIs

**Comment by arnaudbriche** [comment]
@zeroshade it's working fine !
API looks better.

**Comment by arnaudbriche** [comment]
Nothing to do with the PR but just a quick question regarding io API.

Why is  there a requirement for `io.ReadSeekCloser` on `File` ? It seems like `Seek` is not used anywhere, and having to implement it to be compliant with `IO` is a bit annoying.

**Comment by zeroshade** [comment]
The seek is necessary for efficient Parquet processing, and required by the interface APIs for reading Parquet

**Comment by arnaudbriche** [comment]
Ok. I though ReadAt would be sufficient. Thx for answering!

**Comment by zeroshade** [comment]
The only way to get the file length from the file itself is via Seeking to the end unfortunately. 

ReadAt could be sufficient, but would require having to externally provide the file's size somehow.

**Review by zeroshade — APPROVED** [review]
