### PR TITLE
fix(table): remove inconsistencies in metadata serialize

### LINKED ISSUE #345: Inconsistencies in Iceberg metadata serialization
### Apache Iceberg version

None

### Please describe the bug 🐞

Bikeshedding! This is a minor thing, but I think it would be nice to get fixed anyway.

While generating some V1 and V2 metadata, I noticed that for V1, properties serialize to `{}`, while for V2 it is a `null`. For both the field is optional. I think it would be nice to either go for `{}` or leave the keys out.

Although they are consistent, same for `snapshot-log` and `metadata-log`. I think it makes more sense to either leave them out, serialize an empty list.

V1:
```json
{
    "schema": {
        "type": "struct",
        "fields": [
            {
                "type": "int",
                "id": 1,
                "name": "id",
                "required": true
            }
        ],
        "schema-id": 0,
        "identifier-field-ids": []
    },
    "partition-spec": null,
    "format-version": 1,
    "table-uuid": "dd93fa46-a1a7-43bb-8748-6cc7eff107a3",
    "location": "s3a://warehouse/iceberg/iceberg-test-2.db/test-table-2",
    "last-updated-ms": 1742412491193,
    "last-column-id": 1,
    "schemas": [
        {
            "type": "struct",
            "fields": [
                {
                    "type": "int",
                    "id": 1,
                    "name": "id",
                    "required": true
                }
            ],
            "schema-id": 0,
            "identifier-field-ids": []
        }
    ],
    "current-schema-id": 0,
    "partition-specs": [
        {
            "spec-id": 0,
            "fields": []
        }
    ],
    "default-spec-id": 0,
    "last-partition-id": 999,
    "properties": {},
    "snapshot-log": null,
    "metadata-log": null,
    "sort-orders": [
        {
            "order-id": 0,
            "fields": []
        }
    ],
    "default-sort-order-id": 0,
    "refs": null
}
```

V2:
```json
{
    "last-sequence-number": 0,
    "format-version": 2,
    "table-uuid": "afbf8aa3-3786-47fe-b107-48d1efe7b016",
    "location": "s3a://warehouse/iceberg/iceberg-test-2/test-table-2",
    "last-updated-ms": 1742411676663,
    "last-column-id": 1,
    "schemas": [
        {
            "type": "struct",
            "fields": [
                {
                    "type": "int",
                    "id": 1,
                    "name": "id",
                    "required": true
                }
            ],
            "schema-id": 0,
            "identifier-field-ids": []
        }
    ],
    "current-schema-id": 0,
    "partition-specs": [
        {
            "spec-id": 0,
            "fields": []
        }
    ],
    "default-spec-id": 0,
    "last-partition-id": 999,
    "properties": null,
    "snapshot-log": null,
    "metadata-log": null,
    "sort-orders": [
        {
            "order-id": 0,
            "fields": []
        }
    ],
    "default-sort-order-id": 0,
    "refs": null
}
```

### PR DESCRIPTION
**Pull request by zeroshade**
fixes #345

### CODE REVIEW

File: table/metadata.go [hunk 1]
```diff
@@ -1095,7 +1095,7 @@ func (c *commonMetadata) Version() int { return c.FormatVersion }
 
 type metadataV1 struct {
 	Schema    *iceberg.Schema          `json:"schema"`
```
Comment (kevinjqliu) [inline table/metadata.go]:
```suggestion
	Schema    *iceberg.Schema          `json:"schema,omitempty"`
```

since its also omitted in v2/v3
Screenshot 2025-03-20 at 10 16 08 AM

**Review by kevinjqliu — APPROVED** [review]
LGTM

File: table/metadata.go (hunk 1 above)
Comment (zeroshade) [reply table/metadata.go]: it's deprecated, should I still be writing it despite it being deprecated?

Comment (zeroshade) [reply table/metadata.go]: ah, nvm, i see what you mean.

Comment (kevinjqliu) [reply table/metadata.go]: i thought `omitempty` was a way to prevent serializing the field as `"null"`. its still possible for someone to set use the library and set `schema` to `null` and then serialize it to `"null"`, right?
