### PR TITLE
fix(table): fix funky test paths

### LINKED ISSUE #346: Tests generate funky paths
### Apache Iceberg version

None

### Please describe the bug 🐞

Not sure if it is just a test-only thing. From `table_test.go` I changed the temp directory to `/tmp/voooo`, but it seems to encode the metadata in the path 🤔

```
/tmp/voooo/metadata/00001-16fee60d-8467-4851-a0b5-91ed617e5da3.metadata.json/metadata
/tmp/voooo/metadata/00001-16fee60d-8467-4851-a0b5-91ed617e5da3.metadata.json/metadata/snap-4401746492769173237-0-3c2f6c47-c6e2-4e03-9e4f-16c07f6ea64a.avro
/tmp/voooo/metadata/00001-16fee60d-8467-4851-a0b5-91ed617e5da3.metadata.json/metadata/3c2f6c47-c6e2-4e03-9e4f-16c07f6ea64a-m1.avro
/tmp/voooo/metadata/00001-f96c778c-cd6f-48c6-b626-208d4a81db3c.metadata.json
/tmp/voooo/metadata/00001-f96c778c-cd6f-48c6-b626-208d4a81db3c.metadata.json/metadata
/tmp/voooo/metadata/00001-f96c778c-cd6f-48c6-b626-208d4a81db3c.metadata.json/metadata/b67e7d50-ed58-49f3-95ba-056f61980365-m1.avro
/tmp/voooo/metadata/00001-f96c778c-cd6f-48c6-b626-208d4a81db3c.metadata.json/metadata/snap-2988988974226817734-0-b67e7d50-ed58-49f3-95ba-056f61980365.avro
/tmp/voooo/metadata/00001-3ea45a73-bd3a-48d8-ab8c-6d96732aef8b.metadata.json
/tmp/voooo/metadata/00001-3ea45a73-bd3a-48d8-ab8c-6d96732aef8b.metadata.json/metadata
/tmp/voooo/metadata/00001-3ea45a73-bd3a-48d8-ab8c-6d96732aef8b.metadata.json/metadata/snap-2017186713577531619-0-aedac5e5-0d0e-493e-948e-59e85647b027.avro
/tmp/voooo/metadata/00001-3ea45a73-bd3a-48d8-ab8c-6d96732aef8b.metadata.json/metadata/aedac5e5-0d0e-493e-948e-59e85647b027-m1.avro
```

### PR DESCRIPTION
**Pull request by zeroshade**
fixes #346 

Was using the wrong path when generating the Metadata in the tests `createTable` method.

### CODE REVIEW

File: table/table_test.go [hunk 1]
```diff
@@ -280,10 +280,10 @@ func (t *TableWritingTestSuite) writeParquet(fio iceio.WriteFileIO, filePath str
 
 func (t *TableWritingTestSuite) createTable(identifier table.Identifier, formatVersion int, spec iceberg.PartitionSpec, sc *iceberg.Schema) *table.Table {
 	meta, err := table.NewMetadata(sc, &spec, table.UnsortedSortOrder,
-		t.getMetadataLoc(), iceberg.Properties{"format-version": strconv.Itoa(formatVersion)})
+		t.location, iceberg.Properties{"format-version": strconv.Itoa(formatVersion)})
```
Comment (kevinjqliu) [inline table/table_test.go:283]: 👍  table's base location (`t.Location()`) is actually the table metadata's location (`t.metadata.Location()`).

https://github.com/apache/iceberg-go/blob/5142432b98b90b33c3f6af417de4d40aa3be8946/table/table.go#L57-L64

File: table/table_test.go [hunk 2]
```diff
@@ -280,10 +280,10 @@ func (t *TableWritingTestSuite) writeParquet(fio iceio.WriteFileIO, filePath str
...
 	t.Require().NoError(err)
 
-	return table.New(identifier, meta, t.location, iceio.LocalFS{}, nil)
+	return table.New(identifier, meta, t.getMetadataLoc(), iceio.LocalFS{}, nil)
```
Comment (kevinjqliu) [inline table/table_test.go:286]: `table.New`'s `location` parameter overrides tables metadata location
https://github.com/apache/iceberg-go/blob/5142432b98b90b33c3f6af417de4d40aa3be8946/table/table.go#L311-L315

Comment (kevinjqliu) [reply table/table_test.go:286]: this is slightly confusing since a table can have base location, data location, and metadata location.

**Review by kevinjqliu — APPROVED** [review]
LGTM. 

The change makes sense.

File: table/table_test.go (hunk 1 above)
Comment (zeroshade) [reply table/table_test.go:283]: Yea, it's a little weird, but I get the handle on it now. the metadata only knows the table's base location (`t.metadata.Location()`) while the table itself knows the actual location of the metadata json file (`t.metadataLocation`).

File: table/table_test.go (hunk 2 above)
Comment (zeroshade) [reply table/table_test.go:286]: yea, i should probably rename that parameter.

that `location` parameter is *supposed* to be the metadata location. While the tables base location should come from the Metadata that is passed in.
