### PR TITLE
fix(table/scanner): Fix nested field scan

### LINKED ISSUE #309: Support for list types?
### Apache Iceberg version

v0.1.0

### Please describe the bug 🐞

Does the library support scanning tables with fields of type `list`? 

I'm seeing some strange behaviour whilst attempting to scan a table (with all fields selected and no row filters applied) with the following schema:
```
{
    "type": "struct",
    "schema-id": 0,
    "fields": [
        {
            "id": 1,
            "name": "uuid",
            "required": false,
            "type": "string"
        },
        {
            "id": 2,
            "name": "source",
            "required": false,
            "type": {
                "type": "struct",
                "fields": [
                    {
                        "id": 5,
                        "name": "type",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "id": 6,
                        "name": "serviceId",
                        "required": false,
                        "type": "string"
                    }
                ]
            }
        },
        {
            "id": 3,
            "name": "subjects",
            "required": false,
            "type": {
                "type": "list",
                "element-id": 7,
                "element": {
                    "type": "struct",
                    "fields": [
                        {
                            "id": 8,
                            "name": "type",
                            "required": false,
                            "type": "string"
                        },
                        {
                            "id": 9,
                            "name": "id",
                            "required": false,
                            "type": "string"
                        }
                    ]
                },
                "element-required": false
            }
        },
        {
            "id": 4,
            "name": "timing",
            "required": false,
            "type": {
                "type": "struct",
                "fields": [
                    {
                        "id": 10,
                        "name": "createdAt",
                        "required": false,
                        "type": "timestamptz"
                    },
                    {
                        "id": 11,
                        "name": "emittedAt",
                        "required": false,
                        "type": "timestamptz"
                    }
                ]
            }
        }
    ]
}
```

When I call `(*table.Scan).ToArrowRecords` and attempt to loop over the resulting iterator, the loop yields nothing. 

Hooking up a debugger to my code, I can see there's an error being returned by `(*table.Scan).recordsFromTask` ([here](https://github.com/apache/iceberg-go/blob/0921b84b53e3184a1867481bf1e1a22f5a059b5c/table/arrow_scanner.go#L555)) which is resulting in the context being cancelled. Hence, the iterator returns without yielding anything. However, on some occasions it does yield an error, which seems to indicate that there's a race condition between the write to the done channel of the `context.Context` and the write to the `out` channel in `(*table.Scan).recordsFromTask` ([here](https://github.com/apache/iceberg-go/blob/0921b84b53e3184a1867481bf1e1a22f5a059b5c/table/arrow_scanner.go#L377)).

Race condition aside, the error being returned is the following...
```
error encountered during arrow schema visitor: invalid schema: cannot convert list: type=struct<type: utf8, id: utf8>, nullable to Iceberg field, missing field_id
```

I've been doing a bit of digging and noticed an intriguing bit of behaviour with regard to the projected field IDs. It appears that if the field is of type `map` or `list` that it doesn't get added to the set of projected field IDs (see `switch` statement [here](https://github.com/apache/iceberg-go/blob/0921b84b53e3184a1867481bf1e1a22f5a059b5c/table/arrow_scanner.go#L222))? Is this a piece of functionality that is yet to be implemented or is this intended behaviour? Thanks.

### PR DESCRIPTION
**Pull request by zeroshade**
Fixes #309 

There was a combination of factors that caused the initial problem:

1. The arrow-go/v18/parquet/pqarrow library wasn't properly propagating `PARQUET:field_id` metadata for children of List or Map typed fields
2. We only iterated the *fields* and skipped list/maptypes when selecting column indexes, this caused us to miss the children. Instead we need to iterate all of the *field IDs*, this change updates that.
3. When pruning parquet fields we were not propagating the correct ColIndex for map typed columns, we want the leaves so we need the ColIndex of the children
4. creating the output arrays during `ToRequestedSchema` led to a memory leak for list/map columns that needed to be fixed.

A unit test has been added to ensure we are properly able to read the `test_all_types` table and get the rows without error.

### CODE REVIEW

File: table/scanner_test.go [hunk 1]
```diff
@@ -458,6 +458,23 @@ func (s *ScannerSuite) TestPartitionedTables() {
 	}
 }
 
+func (s *ScannerSuite) TestNestedColumns() {
+	mem := memory.NewCheckedAllocator(memory.DefaultAllocator)
+	defer mem.AssertSize(s.T(), 0)
+
+	ident := catalog.ToIdentifier("default", "test_all_types")
```
Comment (kevinjqliu) [inline table/scanner_test.go:465]: is this the nested col?
https://github.com/apache/iceberg-go/blob/b1b432e7164b66a61a00b2a6ed312596661275b1/dev/provision.py#L202

File: table/arrow_utils.go [hunk 2]
```diff
@@ -589,9 +592,9 @@ func SchemaToArrowSchema(sc *iceberg.Schema, metadata map[string]string, include
 // TypeToArrowType converts a given iceberg type, into the equivalent Arrow data type.
 // For dealing with nested fields (List, Struct, Map) if includeFieldIDs is true, then
 // the child fields will contain a metadata key PARQUET:field_id set to the field id.
-func TypeToArrowType(t iceberg.Type, includeFieldIDs bool) (arrow.DataType, error) {
+func TypeToArrowType(t iceberg.Type, includeFieldIDs bool, useLargeTypes bool) (arrow.DataType, error) {
```
Comment (kevinjqliu) [inline table/arrow_utils.go:595]: nit add `useLargeTypes` to docstring above

File: table/arrow_utils.go [hunk 3]
```diff
@@ -497,7 +497,10 @@ func (c convertToArrow) Field(field iceberg.NestedField, result arrow.Field) arr
 
 func (c convertToArrow) List(list iceberg.ListType, elemResult arrow.Field) arrow.Field {
 	elemField := c.Field(list.ElementField(), elemResult)
-	return arrow.Field{Type: arrow.LargeListOfField(elemField)}
+	if c.useLargeTypes {
```
Comment (Fokko) [inline table/arrow_utils.go:500]: I was pretty vocal on this one on the Python side. I strongly believe that we should not expose the options of large types to the user, and that's the [direction that we're heading](https://github.com/apache/iceberg-python/pull/1669) with PyIceberg. In the end, it is up to Arrow to decide if you need large types, or if small types are sufficient.

File: table/scanner_test.go (hunk 1 above)
Comment (zeroshade) [reply table/scanner_test.go:465]: that's one of them. There's also the map and array columns which aren't in the struct. All in all there are several nested columns

File: table/arrow_utils.go (hunk 3 above)
Comment (zeroshade) [reply table/arrow_utils.go:500]: That's actually pretty difficult to do, and would make schema conversion inconsistent.

Determining whether to use the large types cannot be determined until you have the data at which point, if you're streaming the data, it's too late to switch as you can't safely change the schema during a stream. For example:

1. Start reading parquet file with string column, total column data in this file is only 100MB so we use a regular string (small type) and start streaming record batches
2. one of the last files has 3GB of raw data in the string column so we use LargeString for that column from that file
3. We can't cast the LargeString to String, we can't change the schema of the stream to change the column to LargeString, so now we're stuck.

The same problem can occur for List/LargeList depending on the number of total elements in a given column among the lists.

We also can't determine ahead of time by the stats in the iceberg metadata alone whether or not we should use Large types or not. The only way to know ahead of time is to read the parquet file metadata for every data file *before* we start producing record batches and then reconcile whether or not we should use large types before we start processing the files.

It looks like in the pyiceberg PR you linked, if i'm reading it correctly, you just automatically push everything to large types for streaming to avoid the problems I mentioned above? which kinda defeats the benefits if the goal was to avoid using LargeTypes when they aren't needed (in most cases they aren't needed).

**Review by kevinjqliu — APPROVED** [review]
LGTM! I think we can revisit the discussion around large types later since the config is optional
