### PR TITLE
fix(table): prune StatisticsList and PartitionStatsList in RemoveSnapshots

### LINKED ISSUE #836: fix: prune StatisticsList and PartitionStatsList in RemoveSnapshots
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

Parent: #831 

`MetadataBuilder.RemoveSnapshots()` at `metadata.go:488` removes snapshots from the snapshot list and log, but does not prune `StatisticsList` or `PartitionStatsList` entries whose `SnapshotID` matches removed snapshots. This leaves stale statistics entries in table metadata after snapshot expiration.

### PR DESCRIPTION
**Pull request by alliasgher**
## Summary

This PR fixes two related bugs:

**1. `buildCommonMetadata` silently dropped all statistics (primary bug)**

`buildCommonMetadata` in `metadata.go` was not copying `StatisticsList` or `PartitionStatsList` into the rebuilt metadata. This meant *every* `Build()` call — not just `RemoveSnapshots` — silently dropped all statistics files. Any builder operation (add snapshot, update schema, set properties, etc.) would lose statistics on the resulting metadata.

**2. `RemoveSnapshots` left orphaned statistics entries**

Even after fixing the builder, `RemoveSnapshots` would leave stale `StatisticsList`/`PartitionStatsList` entries pointing at snapshots that had just been removed. Added pruning logic consistent with the existing `snapshotList`/`snapshotLog` pattern.

Fixes #836

## Test plan

- [x] `go test ./...`
- [x] `gofmt` clean  
- [x] `TestRemoveSnapshotsPrunesStatistics` — seeds statistics for two snapshots, removes one, asserts the right entry is pruned and the result survives `Build()`.
- [x] `TestBuildPreservesStatistics` — no-op `MetadataBuilderFromBase → Build()` round-trip, asserts statistics are preserved. Pins the `buildCommonMetadata` fix independently of `RemoveSnapshots`.

Signed-off-by: Ali <alliasgher123@gmail.com>

### CODE REVIEW

**Comment by alliasgher** [comment]
The `integration-test` failure is `TestScanner/TestIsInFilterTable` in `scanner_test.go`, an Arrow memory-leak assertion. This test is unrelated to the changes in this PR (which only touch `table/metadata.go` for `RemoveSnapshots` and add a new test in `metadata_builder_internal_test.go`).

The same flake hit #870 on Apr 10. Locally, `go test ./table/` passes cleanly with these changes.

Happy to push an empty commit to retrigger CI, or this can be retried by a maintainer.

File: table/metadata.go [hunk 1]
```diff
@@ -871,6 +884,8 @@ func (b *MetadataBuilder) buildCommonMetadata() (*commonMetadata, error) {
 		SortOrderList:      b.sortOrderList,
 		DefaultSortOrderID: b.defaultSortOrderID,
 		SnapshotRefs:       b.refs,
+		StatisticsList:     b.statisticsList,
+		PartitionStatsList: b.partitionStatsList,
```
Comment (laskoviymishka) [inline table/metadata.go:888]: This is actually the most important line in the PR. 


Before this change, every Build() call silently dropped all statistics from the metadata, not just during RemoveSnapshots, but during ANY builder operation (add snapshot, update schema, etc.). The PR description frames this as a RemoveSnapshots bug, but it's a general metadata builder bug. Worth calling out in the description.

File: table/metadata.go [hunk 2]
```diff
@@ -505,6 +509,15 @@ func (b *MetadataBuilder) RemoveSnapshots(snapshotIds []int64, postCommit bool)
...
 	b.refs = newRefs
 
+	// Prune statistics entries whose snapshot was removed so that table
+	// metadata does not retain stale statistics references.
+	b.statisticsList = slices.DeleteFunc(b.statisticsList, func(e StatisticsFile) bool {
+		return slices.Contains(snapshotIds, e.SnapshotID)
+	})
+	b.partitionStatsList = slices.DeleteFunc(b.partitionStatsList, func(e PartitionStatisticsFile) bool {
+		return slices.Contains(snapshotIds, e.SnapshotID)
+	})
```
Comment (laskoviymishka) [inline table/metadata.go:519]: Consistent with the existing snapshotList/snapshotLog pruning pattern above. Same O(n*m) complexity. Fine for typical use.

File: table/metadata_builder_internal_test.go [hunk 3]
```diff
@@ -622,6 +624,76 @@ func TestRemoveSnapshotRemovesBranch(t *testing.T) {
 	}
 }
 
+// TestRemoveSnapshotsPrunesStatistics verifies that RemoveSnapshots also
+// prunes StatisticsList and PartitionStatsList entries whose SnapshotID
+// matches a removed snapshot. See iceberg-go#836.
+func TestRemoveSnapshotsPrunesStatistics(t *testing.T) {
```
Comment (laskoviymishka) [inline table/metadata_builder_internal_test.go:630]: The test is good — covers load, prune, and build round-trip. 

One thing missing: a test that only does MetadataBuilderFromBase → Build() (no removals) and verifies statistics survive. 

That pins the buildCommonMetadata fix independently of RemoveSnapshots. 

Right now, if someone reverts just the buildCommonMetadata lines but keeps the RemoveSnapshots pruning, this test would still pass (the builder's internal state is correct, but Build() would drop stats) — actually no, the test does call Build() and checks the result. 

So it does cover both. But a separate "no-op round-trip preserves stats" test is clearer about what it'sasserting.

File: table/metadata.go [hunk 4]
```diff
@@ -261,6 +263,8 @@ func MetadataBuilderFromBase(metadata Metadata, currentFileLocation string) (*Me
 	b.refs = maps.Collect(metadata.Refs())
 	b.snapshotLog = slices.Collect(metadata.SnapshotLogs())
 	b.metadataLog = slices.Collect(metadata.PreviousFiles())
+	b.statisticsList = slices.Collect(metadata.Statistics())
+	b.partitionStatsList = slices.Collect(metadata.PartitionStatistics())
```
Comment (laskoviymishka) [inline table/metadata.go:268]: Correct — Statistics() and PartitionStatistics() return iterators over the base metadata's lists. slices.Collect materializes them into owned slices for the builder. Consistent with how snapshotLog and metadataLog are loaded right above.

**Review by laskoviymishka — CHANGES_REQUESTED** [review]
Good catch, this is a real bug. 

But the PR actually fixes two issues, and the undiscussed one is bigger: buildCommonMetadata was not including StatisticsList and PartitionStatsList at all, meaning any metadata rebuild through the builder (not just RemoveSnapshots) silently dropped all statistics. 

The RemoveSnapshots  pruning is the cherry on top.

One ask: add a test for the round-trip bug independently.

File: table/metadata.go (hunk 1 above)
Comment (alliasgher) [reply table/metadata.go:888]: Good call — updated the PR description to lead with the builder bug and frame RemoveSnapshots pruning as the secondary fix.

File: table/metadata.go (hunk 2 above)
Comment (alliasgher) [reply table/metadata.go:519]: Noted.

File: table/metadata_builder_internal_test.go (hunk 3 above)
Comment (alliasgher) [reply table/metadata_builder_internal_test.go:630]: Added `TestBuildPreservesStatistics` in ed1b085 — plain `MetadataBuilderFromBase → Build()` with no mutations, asserts both lists survive.

**Comment by laskoviymishka** [comment]
@tanmayrauth - can you do a round of code review, since you also worked on this item?
since this PR got landed first i think it worth to work on this, or we can do vice-versa with @alliasgher reviewing your PR-s, just try to avoid conflicts here :D

**Review by laskoviymishka — APPROVED** [review]
lgtm now.

**Review by tanmayrauth — APPROVED** [review]
LGTM

**Comment by laskoviymishka** [comment]
I suggests to close - #884 then, let's split credit by finishing some of each of you PR batches.

**Comment by tanmayrauth** [comment]
Thanks @laskoviymishka for resolving it, I will close #884.

**Review by zeroshade — APPROVED** [review]
Thanks!
