### PR TITLE
fix: decode pre-1.4 Java Iceberg legacy manifest list field names (#889)

### LINKED ISSUE #889: ManifestFile cannot read manifest lists written by Iceberg Java before 1.4
### Problem

The Iceberg Java implementation used `added_data_files_count`, `existing_data_files_count`, and `deleted_data_files_count` as field names for manifest list entries (IDs 504/505/506) from its initial release until
apache/iceberg#5338 fixed the names to match the spec in the 1.4 release (merged 2023-10-02). Any table written before that fix, or by an engine still on an older Java version (Athena, some Trino deployments, etc.), has the legacy names embedded in the writer schema of every manifest list OCF file.

### Symptom

When iceberg-go reads such a manifest list, the three count fields decode to zero regardless of their actual values. Downstream this causes `HasAddedFiles()` and `HasExistingFiles()` to return `false`, so fast-append operations silently drop all inherited manifests and `Table.Scan()` returns no data.

### Root cause

hamba/avro's OCF decoder resolves writer-schema field names against struct `avro:` tags. When the writer schema says `added_data_files_count` and the struct tag says `avro:"added_files_count"`, there is no match and the struct field stays zero.

### Fix

Add parallel struct fields with the legacy tags and coalesce in the accessors:

```go
AddedFilesCount        int32 `avro:"added_files_count"`
AddedDataFilesCount    int32 `avro:"added_data_files_count"` // pre-1.4 Java name
```

`AddedDataFiles()` returns `AddedFilesCount` when non-zero, falling back to `AddedDataFilesCount`. Same pattern for existing/deleted. Read-path only, no write-path or schema-registration changes needed.

### Relation to existing issue

apache/iceberg-go#869 fixes the downstream data-loss (manifest inheritance filter in fast-append). This issue fixes the upstream root cause: zero counts when reading pre-1.4 manifest lists in the first place.

### PR DESCRIPTION
**Pull request by tanmayrauth**
Iceberg Java used added_data_files_count, existing_data_files_count, and deleted_data_files_count as manifest list field names (IDs 504/505/506) until apache/iceberg#5338 renamed them to match the spec in the 1.4 release.

Tables written before that fix, or by engines still on older Java versions (Athena, some Trino deployments), embed the legacy names in the writer schema of every manifest list OCF file. When iceberg-go read such a file, hamba/avro could not match writer-schema fields to struct tags and silently left the three count fields at zero.

Zero counts caused HasAddedFiles() and HasExistingFiles() to return false, which broke fast-append manifest inheritance and caused Table.Scan() to return no data.

Fix: add parallel struct fields with the legacy avro tags to manifestFileV1 and manifestFile. Accessors coalesce — preferring the spec-correct name, falling back to the legacy name. No write-path or schema-registration changes are made.

Adds two tests (V1 and V2) that write raw Avro OCF using the pre-1.4 field names and assert the counts decode correctly.

Fixes #889

### CODE REVIEW

**Review by laskoviymishka — CHANGES_REQUESTED** [review]
The fix is correct and the bug is real, but I'd like us to explore a cleaner approach before merging.

The current design adds parallel struct fields + coalescing in every getter. This works, but it's fragile — every accessor needs to remember the fallback logic, and we'd have to repeat it if more legacy field names surface.

hamba/avro supports field-level aliases in schema resolution. Their compatibility test proves it:

```go
// Reader field "aa" with alias ["a"] matches writer field "a" → decoded as "aa"
reader: `{"name": "aa", "type": "int", "aliases": ["a"]}`
writer: `{"name": "a", "type": "int"}`
```

The idea: instead of auto-inferring the avro schema from struct tags, build an explicit reader schema for manifest list files with aliases for legacy names. Then use `SchemaCompatibility.Resolve(reader, writer)` to produce a resolved schema that maps legacy writer fields to spec-correct reader fields automatically.

Concretely, in [`manifest.go` around line 895](https://github.com/tanmayrauth/iceberg-go/blob/699f42666ef1e6b56532a73d1b5a9a3ab827d2bc/manifest.go#L895) where we construct/define the manifest list schema, define an explicit reader schema:

```go
// Reader schema for manifest list files. Uses spec-correct field names
// with aliases for pre-1.4 Java Iceberg legacy names.
func manifestListReaderSchema() *avro.RecordSchema {
    // ... other fields ...
    addedFiles, _ := avro.NewField("added_files_count", avro.NewPrimitiveSchema(avro.Int, nil),
        avro.WithAliases([]string{"added_data_files_count"}))
    existingFiles, _ := avro.NewField("existing_files_count", avro.NewPrimitiveSchema(avro.Int, nil),
        avro.WithAliases([]string{"existing_data_files_count"}))
    deletedFiles, _ := avro.NewField("deleted_files_count", avro.NewPrimitiveSchema(avro.Int, nil),
        avro.WithAliases([]string{"deleted_data_files_count"}))
    // ...
}
```

Then in `ReadManifestList`, after reading the writer schema from the OCF header:

```go
writerSchema := /* from OCF metadata */
readerSchema := manifestListReaderSchema()
resolved, err := avro.NewSchemaCompatibility().Resolve(readerSchema, writerSchema)
// decode records using resolved schema
```

With this approach:
- No parallel struct fields — single `AddedFilesCount` with `avro:"added_files_count"`
- No coalescing in getters — they stay as one-liners
- hamba/avro handles the mapping at the schema level, which is where Avro is designed to solve this
- If more legacy names appear in the future, it's one alias declaration, not N getter changes

This is more work upfront than the current approach, but it's the right abstraction layer for this problem. Worth exploring before we commit to the parallel-fields pattern. If it turns out to be too much plumbing for the OCF decoder, we can fall back to post-decode normalization (single `normalizeLegacyFields()` call after decode, instead of per-getter coalescing).

**Comment by zeroshade** [comment]
I agree with @laskoviymishka's approach here. In addition, we recently updated to a different avro library #871 so we should double check how this works in that library @twmb can you comment?

**Comment by twmb** [comment]
twmb/avro supports aliases on decode as well, usable via schema resolution. The arg ordering is different in my Resolve (though in research mine matches the ecosystem more broadly).

One "downside", maybe (it's more spec correct but less lenient), of my repo vs. hamba is that twmb/avro is stricter when decoding writer-schema record fields that are missing from the struct being decoded into (reader-schema) - twmb/avro will error when trying to decode `added_data_files_count` into a struct that doesn't have that field (i.e. the silent bug that this PR is about).

The complication with the approach proposed in the comment above is that we need to read the ocf header to know what schema to use / what struct to decode into, but the existing `ocf.WithReaderSchema` needs the reader schema up front (hamba/avro has the same limitation), which means the cleanest wiring needs either a buffer-and-reopen dance or a new API in twmb/avro.

So, I'm adding `WithReaderSchemaFunc` option to twmb/avro's ocf package (to be released as 1.6.0 imminently, hopefully the last minor release for a while ...). The callback is invoked after the ocf header has been parsed: `rd.Schema()` returns the writer schema, `rd.Metadata()` is populated, and whatever schema it returns becomes the reader schema for resolution.

With that option, `ReadManifestList` becomes something like:

```go
type manifestFileV1 struct {
    // ...
    AddedFilesCount    *int32 `avro:"added_files_count,alias=added_data_files_count"`
    ExistingFilesCount *int32 `avro:"existing_files_count,alias=existing_data_files_count"`
    DeletedFilesCount  *int32 `avro:"deleted_files_count,alias=deleted_data_files_count"`
    // ...
}

type manifestFile struct {
    // ...
    AddedFilesCount    int32 `avro:"added_files_count,alias=added_data_files_count"`
    ExistingFilesCount int32 `avro:"existing_files_count,alias=existing_data_files_count"`
    DeletedFilesCount  int32 `avro:"deleted_files_count,alias=deleted_data_files_count"`
    // ...
}

var (
    manifestFileV1Reader = avro.MustSchemaFor[manifestFileV1]()
    manifestFileReader   = avro.MustSchemaFor[manifestFile]()
)

func ReadManifestList(in io.Reader) ([]ManifestFile, error) {
    var version int

    rd, err := ocf.NewReader(in, ocf.WithReaderSchemaFunc(func(rd *ocf.Reader) (*avro.Schema, error) {
        version = 1
        if raw := rd.Metadata()["format-version"]; len(raw) > 0 {
            v, err := strconv.Atoi(string(raw))
            if err != nil {
                return nil, fmt.Errorf("invalid format-version: %w", err)
            }
            version = v
        }
        if version == 1 {
            return manifestFileV1Reader, nil
        }
        return manifestFileReader, nil
    }))
    if err != nil {
        return nil, err
    }

    switch version {
    case 1:
        return decodeManifestsWithFallback[*manifestFileV1](rd)
    default:
        return decodeManifests[*manifestFile](rd, version)
    }
}
```

**Comment by zeroshade** [comment]
@tanmayrauth would you be able to leverage @twmb's [comment](https://github.com/apache/iceberg-go/pull/890#issuecomment-4246697937) to update this appropriately?

**Comment by twmb** [comment]
v1.6.0 has been pushed, if you want to update and use the WithSchemaReaderFunc option.

**Comment by tanmayrauth** [comment]
Thanks @zeroshade @twmb @laskoviymishka , this totally makes sense. I will update the PR.

**Comment by tanmayrauth** [comment]
@zeroshade  @laskoviymishka  I've updated the PR with review comments

File: manifest.go [hunk 1]
```diff
@@ -537,27 +485,37 @@ type ManifestFile interface {
...
+// manifestFileV1Reader is the Avro reader schema for V1 manifest list entries.
+// It handles both spec-correct field names and pre-1.4 Java Iceberg legacy
+// names (added_data_files_count etc.) via the alias tags on manifestFileV1,
+// and both nullable and non-nullable added_snapshot_id via *int64.
+var manifestFileV1Reader = avro.MustSchemaFor[manifestFileV1](
+	avro.WithName("manifest_file"),
+	avro.CustomType{
+		GoType: reflect.TypeOf(FieldSummary{}),
+		Schema: &fieldSummarySchemaNode,
+	},
```
Comment (twmb) [inline manifest.go]: Interesting, I didn't even think about how CustomType could be used for this.
I can add a `type-alias` tag so that this can just become
```go
var manifestFileV1Reader = avro.MustSchemaFor[manifestFileV1](
    avro.WithName("manifest_file"),
)
```

and then the struct would be
```
PartitionList *[]FieldSummary `avro:"partitions,type-alias=r508"
```

doesn't need to block this PR though.

**Comment by tanmayrauth** [comment]
@zeroshade if the changes looks good now, can we please merge this?

File: manifest.go (hunk 1 above)
Comment (twmb) [reply manifest.go]: I've pushed v1.7.0 if you want to add the type-alias tag and simplify this code significantly

Comment (tanmayrauth) [reply manifest.go]: Sure, let me do it. Thanks for updating it.

Comment (tanmayrauth) [reply manifest.go]: I got it updated

**Comment by tanmayrauth** [comment]
> I agree with @laskoviymishka's approach here. In addition, we recently updated to a different avro library #871 so we should double check how this works in that library @twmb can you comment?

@zeroshade   I've incorporated  the suggested changes, could we please merge this PR?

File: manifest.go [hunk 2]
```diff
@@ -537,27 +485,21 @@ type ManifestFile interface {
...
-	for {
-		tmp := P(new(T))
-		if err := rd.Decode(tmp); err != nil {
-			if errors.Is(err, io.EOF) {
-				return results, nil
-			}
-
-			return nil, err
-		}
+// fieldSummarySchemaNode is the FieldSummary Avro schema with "r508" as an
```
Comment (laskoviymishka) [inline manifest.go]: [nit] first two lines describe fieldSummarySchemaNode — a variable from the intermediate version that was removed when type-alias=r508 tag replaced it. The sentence is incomplete ("...match the record name used by the") and then a new sentence about manifestFileV1Reader starts. Maybe just delete this?

**Review by laskoviymishka — APPROVED** [review]
The approach is right, the avro library changes are solid, tests cover the fix. One nit to cleanup garbled comment, otherwise -- ready to merge.

File: manifest.go [hunk 3]
```diff
@@ -158,154 +158,81 @@ func (b *ManifestBuilder) Build() ManifestFile {
...
-	AddedFilesCount    *int32 `avro:"added_files_count"`
-	ExistingFilesCount *int32 `avro:"existing_files_count"`
-	DeletedFilesCount  *int32 `avro:"deleted_files_count"`
-	AddedRowsCount     *int64 `avro:"added_rows_count"`
-	ExistingRowsCount  *int64 `avro:"existing_rows_count"`
-	DeletedRowsCount   *int64 `avro:"deleted_rows_count"`
+	Path               string          `avro:"manifest_path"`
+	Len                int64           `avro:"manifest_length"`
+	SpecID             int32           `avro:"partition_spec_id"`
+	AddedSnapshotID    *int64          `avro:"added_snapshot_id"`
```
Comment (zeroshade) [inline manifest.go:169]: Isn't `AddedSnapshotId` required in v1? Will this break if the avro schema has it as required vs optional? Previously we relied on embedding the `manifestFile` version that had it as required and then fell back if it was optional. But we don't want this to break on v1 manifests that have it as required.

File: manifest.go [hunk 4]
```diff
@@ -316,14 +243,14 @@ type manifestFile struct {
...
+	AddedFilesCount    int32           `avro:"added_files_count,alias=added_data_files_count"`
+	ExistingFilesCount int32           `avro:"existing_files_count,alias=existing_data_files_count"`
+	DeletedFilesCount  int32           `avro:"deleted_files_count,alias=deleted_data_files_count"`
 	AddedRowsCount     int64           `avro:"added_rows_count"`
 	ExistingRowsCount  int64           `avro:"existing_rows_count"`
 	DeletedRowsCount   int64           `avro:"deleted_rows_count"`
-	PartitionList      *[]FieldSummary `avro:"partitions"`
-	Key                []byte          `avro:"key_metadata"`
+	PartitionList      *[]FieldSummary `avro:"partitions,type-alias=r508"`
+	Key                *[]byte         `avro:"key_metadata"`
```
Comment (zeroshade) [inline manifest.go]: why this change?

File: manifest.go [hunk 5]
```diff
@@ -384,15 +311,30 @@ func (m *manifestFile) Length() int64                    { return m.Len }
...
+	return m.AddedFilesCount
+}
+
+func (m *manifestFile) ExistingDataFiles() int32 {
+	return m.ExistingFilesCount
+}
+
+func (m *manifestFile) DeletedDataFiles() int32 {
+	return m.DeletedFilesCount
+}
```
Comment (zeroshade) [inline manifest.go]: why change this formatting?

File: manifest.go [hunk 6]
```diff
@@ -401,8 +343,14 @@ func (m *manifestFile) Partitions() []FieldSummary {
...
-func (m *manifestFile) HasAddedFiles() bool    { return m.AddedFilesCount != 0 }
-func (m *manifestFile) HasExistingFiles() bool { return m.ExistingFilesCount != 0 }
+func (m *manifestFile) HasAddedFiles() bool {
+	return m.AddedFilesCount != 0
+}
+
+func (m *manifestFile) HasExistingFiles() bool {
+	return m.ExistingFilesCount != 0
+}
+
```
Comment (zeroshade) [inline manifest.go]: why change this formatting?

File: manifest.go [hunk 7]
```diff
@@ -811,43 +753,46 @@ func ReadManifest(m ManifestFile, f io.Reader, discardDeleted bool) ([]ManifestE
...
-	version := 1
-	if raw := rd.Metadata()["format-version"]; len(raw) > 0 {
-		version, err = strconv.Atoi(string(raw))
-		if err != nil {
-			return nil, fmt.Errorf("invalid format-version: %w", err)
+		if version == 1 {
+			return manifestFileV1Reader, nil
 		}
+
+		return manifestFileReader, nil
```
Comment (zeroshade) [inline manifest.go:807]: are we going to have to do this for every version?

File: manifest.go [hunk 8]
```diff
@@ -811,43 +753,46 @@ func ReadManifest(m ManifestFile, f io.Reader, discardDeleted bool) ([]ManifestE
...
+			if err := rd.Decode(tmp); err != nil {
+				if errors.Is(err, io.EOF) {
+					return results, nil
 				}
 
-				break
+				return nil, err
 			}
+
+			results = append(results, tmp.toFile())
```
Comment (zeroshade) [inline manifest.go]: Isn't this just `decodeManifestsWithFallback[*manifestFileV1](rd)`? Can't we just leave the switch we had below?

**Review by zeroshade — CHANGES_REQUESTED** [review]

File: manifest.go (hunk 3 above)
Comment (tanmayrauth) [reply manifest.go:169]: Since we now use ocf.WithReaderSchemaFunc for schema resolution, Avro handles promotion of required long → ["null", "long"] automatically. When the writer has added_snapshot_id as required, the decoded pointer will always be non-nil. The old fallbackManifestFileV1 was needed because the  code decoded without schema resolution and had to inspect the writer schema at runtime.

File: manifest.go (hunk 6 above)
Comment (tanmayrauth) [reply manifest.go]: Fixed. Reverted to single-line formatting these were rebase artifacts.

File: manifest.go (hunk 5 above)
Comment (tanmayrauth) [reply manifest.go]: Fixed. Reverted to single-line formatting.

File: manifest.go (hunk 7 above)
Comment (tanmayrauth) [reply manifest.go:807]: manifestFileReader already covers V2 and V3 since manifestFile includes all fields like FirstRowIDValue. Only V1 needs a separate reader schema because its fields use pointer types for nullable unions. Future spec versions would only need a new branch here if they introduced fundamentally different field layouts.

File: manifest.go (hunk 8 above)
Comment (tanmayrauth) [reply manifest.go]: Fixed. Extracted inline loop into decodeV1Manifests() helper. The old decodeManifestsWithFallback couldn't be reused because its type constraint required ManifestFile interface implementation, which manifestFileV1 no longer satisfies (it's now a pure deserialization struct that converts via toFile()). The new decodeV1Manifests is simpler and purpose-built.

**Comment by tanmayrauth** [comment]
@zeroshade  does the changes looks fine now?

**Review by zeroshade — APPROVED** [review]
