### PR TITLE
 fix: Azure URI parsing with `KeyExtractor` function for `blobFileIO` preprocessing

### LINKED ISSUE #561: Azure Blob Storage URI Handling in createBlobFs Causes Incorrect Paths and Metadata Mismatch
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

The current implementation of `createBlobFs` in [io/blob.go](https://github.com/apache/iceberg-go/blob/main/io/blob.go) incorrectly handles [Azure Blob Storage URIs](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction-abfs-uri#uri-syntax), causing a mismatch between the actual object storage paths and those recorded in Iceberg table metadata. 
This leads to failures when reading the table with engines like Trino or Spark.

Currently, createBlobFs takes bucketName and uses it to strip a prefix from the full path of a file.
However, in the case of an Azure URI, we need to strip `<bucketName>@<account>.<domain>` instead.

## Example
Given:
```
abfss://mycontainer@myaccount.blob.core.windows.net/<key>
```
The file is written to:
```
https://myaccount.blob.core.windows.net/mycontainer/mycontainer@myaccount.dfs.core.windows.net/<key>
```

### PR DESCRIPTION
**Pull request by alessandro-nori**
## Summary

- Replace `bucketName` field with injectable KeyExtractor function in blobFileIO
- Add `adlsKeyExtractor` for Azure schemes using regex pattern from Java implementation  

## Testing
- [x] All existing tests pass
- [x] New unit tests for defaultKeyExtractor and adlsKeyExtractor

Fixes #561

### CODE REVIEW

File: io/azure.go [hunk 1]
```diff
@@ -184,3 +189,18 @@ func createAzureBucket(ctx context.Context, parsed *url.URL, props map[string]st
...
 	return azureblob.OpenBucket(ctx, client, nil)
 }
+
+// adlsKeyExtractor creates a key extractor for Azure schemes using the adlsURIPattern pattern
+func adlsKeyExtractor() KeyExtractor {
+	return func(path string) (string, error) {
+		matches := adlsURIPattern.FindStringSubmatch(path)
+		if len(matches) < 4 {
+			// If it doesn't match Azure pattern, return path as-is
+			return "", fmt.Errorf("invalid ADLS location: %s", path)
```
Comment (twuebi) [inline io/azure.go]: The comment and the return statement don't match up, right?

File: io/azure_test.go [hunk 2]
```diff
@@ -145,3 +145,58 @@ func TestNewAdlsLocationUriParsing(t *testing.T) {
...
+		},
+		{
+			name:        "wasbs valid URI",
+			input:       "wasbs://container@account.blob.core.windows.net/path/to/file.parquet",
+			expectedKey: "path/to/file.parquet",
+		},
+		{
+			name:        "URI with no path",
+			input:       "abfs://container@account.dfs.core.windows.net",
+			expectedKey: "",
```
Comment (twuebi) [inline io/azure_test.go]: Why is this no error?

File: io/azure.go (hunk 1 above)
Comment (alessandro-nori) [reply io/azure.go]: 🙇 right, I changed the code but forgot to remove the comment

File: io/azure_test.go (hunk 2 above)
Comment (alessandro-nori) [reply io/azure_test.go]: I followed the Java implementation and it returns an empty string in case of empty/null path.
https://github.com/apache/iceberg/blob/723d0998d69f254822efd6f8939e71c0723aaab2/azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java#L79

I think in our specific case it is ok to return an error and I'll update the code if we agree on it

Comment (mrcnc) [reply io/azure_test.go]: I think an error would be helpful here b/c it's not a valid location for any file that would be tracked in an Iceberg table.  Also, the Java implementation could improve its validation logic so there's not a strong reason to copy it here

Comment (zeroshade) [reply io/azure_test.go]: I agree, let's update this to return an error in this case
